// This file is auto-generated by barrel-craft. Edit only if you are sure.

export * from './CreateRelationUseCase'
export * from './DeleteRelationUseCase'
export * from './GetRelationsByCharIdUseCase'
export * from './GetRelationUseCase'
export * from './UpdateRelationUseCase'
