ALTER TABLE "chapters" ADD COLUMN "rank" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ADD COLUMN "rank" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "stats" ADD COLUMN "rank" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "story_schema_fields" ADD COLUMN "rank" text DEFAULT '' NOT NULL;--> statement-breakpoint
-- Ranks for rows written before ranks existed: the key each old position implies (rules/rank.ts legacyRank), then positions renumbered from the ranks, and tombstones placeless.
UPDATE "scenes" SET "rank" = CASE WHEN GREATEST("index", 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (GREATEST("index", 0)) + 1, 1) WHEN GREATEST("index", 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((GREATEST("index", 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((GREATEST("index", 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((LEAST(GREATEST("index", 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((LEAST(GREATEST("index", 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((LEAST(GREATEST("index", 0), 242233) - 3906) % 62) + 1, 1) END WHERE "rank" = '';
--> statement-breakpoint
UPDATE "chapters" SET "rank" = CASE WHEN GREATEST("index", 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (GREATEST("index", 0)) + 1, 1) WHEN GREATEST("index", 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((GREATEST("index", 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((GREATEST("index", 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((LEAST(GREATEST("index", 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((LEAST(GREATEST("index", 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((LEAST(GREATEST("index", 0), 242233) - 3906) % 62) + 1, 1) END WHERE "rank" = '';
--> statement-breakpoint
UPDATE "stats" SET "rank" = CASE WHEN GREATEST("order" + 1, 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (GREATEST("order" + 1, 0)) + 1, 1) WHEN GREATEST("order" + 1, 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((GREATEST("order" + 1, 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((GREATEST("order" + 1, 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((LEAST(GREATEST("order" + 1, 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((LEAST(GREATEST("order" + 1, 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((LEAST(GREATEST("order" + 1, 0), 242233) - 3906) % 62) + 1, 1) END WHERE "rank" = '';
--> statement-breakpoint
UPDATE "story_schema_fields" SET "rank" = CASE WHEN GREATEST("order" + 1, 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (GREATEST("order" + 1, 0)) + 1, 1) WHEN GREATEST("order" + 1, 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((GREATEST("order" + 1, 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((GREATEST("order" + 1, 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((LEAST(GREATEST("order" + 1, 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((LEAST(GREATEST("order" + 1, 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((LEAST(GREATEST("order" + 1, 0), 242233) - 3906) % 62) + 1, 1) END WHERE "rank" = '';
--> statement-breakpoint
UPDATE "scenes" SET "index" = 0 WHERE "is_deleted" = true AND "index" <> 0;
--> statement-breakpoint
UPDATE "chapters" SET "index" = 0 WHERE "is_deleted" = true AND "index" <> 0;
--> statement-breakpoint
UPDATE "stats" SET "order" = -1 WHERE "is_deleted" = true AND "order" <> -1;
--> statement-breakpoint
UPDATE "story_schema_fields" SET "order" = -1 WHERE "is_deleted" = true AND "order" <> -1;
--> statement-breakpoint
UPDATE "scenes" SET "index" = "numbered"."position" FROM (SELECT "id", ROW_NUMBER() OVER (PARTITION BY "story_id", "chapter_id" ORDER BY "rank" COLLATE "C", "id" COLLATE "C") AS "position" FROM "scenes" WHERE "is_deleted" = false) AS "numbered" WHERE "scenes"."id" = "numbered"."id" AND "scenes"."index" <> "numbered"."position";
--> statement-breakpoint
UPDATE "chapters" SET "index" = "numbered"."position" FROM (SELECT "id", ROW_NUMBER() OVER (PARTITION BY "story_id", "type" ORDER BY "rank" COLLATE "C", "id" COLLATE "C") AS "position" FROM "chapters" WHERE "is_deleted" = false) AS "numbered" WHERE "chapters"."id" = "numbered"."id" AND "chapters"."index" <> "numbered"."position";
--> statement-breakpoint
UPDATE "stats" SET "order" = "numbered"."position" FROM (SELECT "id", ROW_NUMBER() OVER (PARTITION BY "story_id" ORDER BY "rank" COLLATE "C", "id" COLLATE "C") - 1 AS "position" FROM "stats" WHERE "is_deleted" = false) AS "numbered" WHERE "stats"."id" = "numbered"."id" AND "stats"."order" <> "numbered"."position";
--> statement-breakpoint
UPDATE "story_schema_fields" SET "order" = "numbered"."position" FROM (SELECT "id", ROW_NUMBER() OVER (PARTITION BY "story_id", "entity_type" ORDER BY "rank" COLLATE "C", "id" COLLATE "C") - 1 AS "position" FROM "story_schema_fields" WHERE "is_deleted" = false) AS "numbered" WHERE "story_schema_fields"."id" = "numbered"."id" AND "story_schema_fields"."order" <> "numbered"."position";
