version: '3.9'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://user:pass@db/nestdb
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=nestdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
