export enum OperationLogEntityType {
  Story = 'Story',
  Character = 'Character',
  Note = 'Note',
  Location = 'Location',
  WorldRule = 'WorldRule',
  Tag = 'Tag',
  User = 'User',
  Chapter = 'Chapter',
  Scene = 'Scene',
  Choice = 'Choice',
  Gallery = 'Gallery',
  GalleryRelation = 'GalleryRelation',
  Item = 'Item',
  CharacterRelation = 'CharacterRelation',
  TagRelation = 'TagRelation',
  NoteRelation = 'NoteRelation',
  OperationLog = 'OperationLog',
  ItemJourney = 'ItemJourney',
  CharacterScene = 'CharacterScene',
  StorySchemaField = 'StorySchemaField',
  AttributeValue = 'AttributeValue',
  LocationRelation = 'LocationRelation',
  Favorite = 'Favorite',
  Suggestion = 'Suggestion',
  SeeAlsoRelation = 'SeeAlsoRelation',
  Comment = 'Comment',
  ChoiceCheckGroup = 'ChoiceCheckGroup',
  ChoiceCheck = 'ChoiceCheck',
  Effect = 'Effect',
  // Add other relevant entities as they are introduced to the system
}
