import { StoryDeviceSection } from './types';

export const storyDeviceSections: StoryDeviceSection[] = [
  {
    id: 'start',
    titleKey: 'story_devices_section_start',
    icon: 'book-outline',
    pageIds: ['how-to-use-devices'],
  },
  {
    id: 'structure',
    titleKey: 'story_devices_section_structure',
    icon: 'map-outline',
    pageIds: [
      'three-act-structure',
      'freytags-pyramid',
      'heros-journey',
      'story-circle',
      'seven-point-structure',
      'save-the-cat-beat-sheet',
      'fichtean-curve',
      'kishotenketsu',
      'heroines-journey',
      'in-media-res',
      'refusal-of-the-call',
      'frame-story',
    ],
  },
  {
    id: 'plot',
    titleKey: 'story_devices_section_plot',
    icon: 'git-network-outline',
    pageIds: [
      'chekhovs-gun',
      'setup-and-payoff',
      'foreshadowing',
      'red-herring',
      'macguffin',
      'dramatic-irony',
      'ticking-clock',
      'cliffhanger',
      'role-reversal',
      'impossible-choice',
      'deus-ex-machina',
    ],
  },
  {
    id: 'character',
    titleKey: 'story_devices_section_character',
    icon: 'person-outline',
    pageIds: [
      'want-vs-need',
      'the-wound',
      'character-arc',
      'flat-arc',
      'the-foil',
      'save-the-cat',
      'kick-the-dog',
      'pet-the-dog',
      'mary-sue',
    ],
  },
  {
    id: 'scene',
    titleKey: 'story_devices_section_scene',
    icon: 'film-outline',
    pageIds: [
      'show-dont-tell',
      'in-late-out-early',
      'scene-and-sequel',
      'sensory-grounding',
      'subtext',
      'dialogue-beats',
      'iceberg-theory',
      'lampshading',
    ],
  },
  {
    id: 'style',
    titleKey: 'story_devices_section_style',
    icon: 'color-wand-outline',
    pageIds: [
      'pacing',
      'rule-of-three',
      'chapter-hook',
      'point-of-view',
      'narrative-voice',
      'unreliable-narrator',
      'motif-and-leitmotif',
      'subversion-of-tropes',
    ],
  },
  {
    id: 'theme',
    titleKey: 'story_devices_section_theme',
    icon: 'sparkles-outline',
    pageIds: [
      'theme-statement',
      'thematic-mirror',
      'hobsons-choice',
      'kill-the-mentor',
      'bookending',
    ],
  },
];

export const storyDevicePageIds = storyDeviceSections.flatMap((section) => section.pageIds);
