import { mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';

export interface DocRegistryOptions {
  contentDir: string;
  outputFile: string;
  typeName: string;
  registryName: string;
  pageTypeImport: string;
}

/**
 * Generates the registry of a documentation library (Help or Literary Devices) from the
 * content folders: one folder per page, one file per language.
 */
export function generateDocRegistry({
  contentDir,
  outputFile,
  typeName,
  registryName,
  pageTypeImport,
}: DocRegistryOptions): void {
  mkdirSync(dirname(outputFile), { recursive: true });
  const toName = (id: string, language: string) =>
    `${id.replace(/[^a-zA-Z0-9]+(.)?/g, (_, char: string | undefined) => (char ? char.toUpperCase() : ''))}_${language}`;
  const propertyKey = (value: string) =>
    /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : `'${value.replace(/'/g, "'")}'`;
  const ids = readdirSync(contentDir)
    .filter((entry) => statSync(join(contentDir, entry)).isDirectory())
    .sort();

  let imports = '';
  let entries = '';
  for (const id of ids) {
    const languages = readdirSync(join(contentDir, id))
      .filter((file) => file.endsWith('.ts'))
      .map((file) => basename(file, '.ts'))
      .sort();
    const languageEntries = languages
      .map((language) => {
        const name = toName(id, language);
        imports += `import ${name} from '../content/${id}/${language}';\n`;
        return `    ${propertyKey(language)}: ${name},`;
      })
      .join('\n');
    entries += `  ${propertyKey(id)}: {\n${languageEntries}\n  },\n`;
  }

  const union = ids.length ? `\n${ids.map((id) => `  | '${id}'`).join('\n')}` : 'never';
  writeFileSync(
    outputFile,
    `// Auto-generated by generate-indexes.ts. Do not edit.\n${pageTypeImport}\n\n${imports}\nexport type ${typeName} =${union};\n\nexport const ${registryName}: Record<${typeName}, Record<string, HelpPage>> = {\n${entries}};\n`,
  );
  console.log(`Generated registry with ${ids.length} pages at ${outputFile}`);
}
