export const exampleStoryLocalizedText = {
  en: {
    plotNames: ['Main conflict', 'Inner change', 'Hidden consequence', 'Unused possibility'],
    plotDetails: [
      'The broad causal thread that carries the story from opening to resolution.',
      'The emotional change that appears at selected turning points.',
      'A late thread concentrated near the resolution.',
      'An intentionally empty plot used to demonstrate planning before scenes are assigned.',
    ],
    plotNotes: [
      'Introduces the thread',
      'Develops the thread',
      'Changes its direction',
      'Resolves it',
    ],
    comments: [
      'Useful foundation; preserve this fact during revision.',
      'Check whether the transition is sufficiently clear.',
      'Resolve this continuity risk before publication.',
      'This detail should echo in a later scene.',
    ],
    schema: {
      names: [
        'Theme note',
        'Editorial analysis',
        'Narrative weight',
        'Resolved',
        'Review date',
        'Arc',
        'Motifs',
        'Reference place',
      ],
      descriptions: [
        'Short thematic label',
        'Long-form editorial observation',
        'Relative narrative importance',
        'Whether the point is resolved',
        'Planned review date',
        'Controlled arc value',
        'Several controlled motifs',
        'Related location',
      ],
      suggestionValues: ['Growth', 'Duty', 'Discovery', 'Reconciliation'],
      listValues: ['Promise', 'Threshold', 'Transformation', 'Return'],
    },
    statNames: ['Resolve', 'Insight', 'Influence', 'Agility', 'Fortune'],
    modeNames: ['Under pressure', 'Transformed'],
    modeChanges: [
      'Acts with urgency and accepts greater risks.',
      'A decisive experience changes priorities and abilities.',
    ],
  },
  pt: {
    plotNames: [
      'Conflito principal',
      'Mudança interior',
      'Consequência oculta',
      'Possibilidade não usada',
    ],
    plotDetails: [
      'O amplo fio causal que conduz a história da abertura à resolução.',
      'A mudança emocional que aparece em pontos de virada selecionados.',
      'Um fio tardio concentrado próximo à resolução.',
      'Uma trama intencionalmente vazia para demonstrar o planejamento antes de atribuir cenas.',
    ],
    plotNotes: ['Introduz o fio', 'Desenvolve o fio', 'Muda sua direção', 'Resolve o fio'],
    comments: [
      'Base útil; preserve este fato durante a revisão.',
      'Verifique se a transição está suficientemente clara.',
      'Resolva este risco de continuidade antes da publicação.',
      'Este detalhe deveria repercutir em uma cena posterior.',
    ],
    schema: {
      names: [
        'Nota temática',
        'Análise editorial',
        'Peso narrativo',
        'Resolvido',
        'Data de revisão',
        'Arco',
        'Motivos',
        'Local de referência',
      ],
      descriptions: [
        'Rótulo temático curto',
        'Observação editorial extensa',
        'Importância narrativa relativa',
        'Se o ponto está resolvido',
        'Data planejada para revisão',
        'Valor controlado de arco',
        'Vários motivos controlados',
        'Local relacionado',
      ],
      suggestionValues: ['Crescimento', 'Dever', 'Descoberta', 'Reconciliação'],
      listValues: ['Promessa', 'Limiar', 'Transformação', 'Retorno'],
    },
    statNames: ['Determinação', 'Percepção', 'Influência', 'Agilidade', 'Fortuna'],
    modeNames: ['Sob pressão', 'Transformado'],
    modeChanges: [
      'Age com urgência e aceita riscos maiores.',
      'Uma experiência decisiva muda prioridades e habilidades.',
    ],
  },
} as const;
