import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

/**
 * The index of the example stories: one folder per story in `content/<slug>/`, and one
 * `<lang>.json` inside it per language.
 *
 * Unlike the other catalogues it does not `import` the stories. A packaged story is ~90 KB of JSON,
 * the twelve of them over a megabyte, and a person installs one of them once, if ever - yet a static
 * `import` puts all of it in the bundle everybody downloads and parses at start. So each language
 * entry carries what the list needs to draw its card (`meta`, copied out of the file here) and a
 * `load()` that fetches the story itself when it is installed. Metro turns each `import()` into a
 * chunk on the web, and on the phone and in the desktop shell it resolves inside the app: nothing
 * to download there.
 *
 * Metro still needs a literal string in each `import()`, which is why the folder scan happens here,
 * before the build, and not on the device.
 */
export interface ExampleStoryMeta {
  title: unknown;
  description: unknown;
  type: unknown;
  author: unknown;
}

/** What the example list shows of a story, read straight from its file (the rest is read on install). */
export function readExampleStoryMeta(file: string): ExampleStoryMeta {
  const story = (JSON.parse(readFileSync(file, 'utf8')) as { story?: Record<string, unknown> })
    ?.story;
  return {
    title: story?.title ?? null,
    description: story?.description ?? null,
    type: story?.type ?? null,
    author: story?.author ?? null,
  };
}

export function renderExampleStoriesIndex(contentDir: string): {
  source: string;
  storyCount: number;
} {
  const slugs = existsSync(contentDir)
    ? readdirSync(contentDir)
        .filter((entry) => statSync(join(contentDir, entry)).isDirectory())
        .sort()
    : [];

  let entries = '';
  let storyCount = 0;
  for (const slug of slugs) {
    const languageFiles = readdirSync(join(contentDir, slug))
      .filter((file) => file.endsWith('.json'))
      .sort();
    if (languageFiles.length === 0) continue;
    storyCount += 1;

    const languageLines = languageFiles
      .map((file) => {
        const language = basename(file, '.json');
        const meta = JSON.stringify(readExampleStoryMeta(join(contentDir, slug, file)));
        return `      {
        language: '${language}',
        meta: ${meta},
        load: () => import('../content/${slug}/${file}').then((module) => module.default),
      },`;
      })
      .join('\n');

    entries += `  {
    slug: '${slug}',
    languages: [
${languageLines}
    ],
  },
`;
  }

  return {
    storyCount,
    source: `// This file is auto-generated by generate-indexes.ts
// Do not modify this file directly.
import type { ExampleStoryEntry } from '../types';

export const exampleStoryRegistry: ExampleStoryEntry[] = [
${entries.trimEnd()}
];
`,
  };
}

export function generateExampleStoriesIndex(clientRoot: string): void {
  console.log('Generating example stories registry...');
  const outputFile = join(clientRoot, 'src/exampleStories/generated/registry.ts');
  mkdirSync(join(outputFile, '..'), { recursive: true });
  const { source, storyCount } = renderExampleStoriesIndex(
    join(clientRoot, 'src/exampleStories/content'),
  );
  writeFileSync(outputFile, source);
  console.log(
    `Example stories registry generated successfully (${storyCount} example stor${storyCount === 1 ? 'y' : 'ies'}) at: ${outputFile}`,
  );
}
