import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

/**
 * Writes the index of the example stories: one folder per story in `content/<slug>/`, and one
 * `<lang>.json` inside it per language.
 *
 * The same reason as the migrations index: Metro needs a static `import`, so the folder scan happens
 * here, before the build, and not on the device.
 */
export function generateExampleStoriesIndex(clientRoot: string): void {
  const contentDirectory = join(clientRoot, 'src/exampleStories/content');
  const generatedDirectory = join(clientRoot, 'src/exampleStories/generated');
  const outputFile = join(generatedDirectory, 'registry.ts');

  console.log('Generating example stories registry...');
  mkdirSync(generatedDirectory, { recursive: true });

  const toImportName = (slug: string, language: string) => {
    const camel = slug.replace(/[^a-zA-Z0-9]+(.)?/g, (_, char: string | undefined) =>
      char ? char.toUpperCase() : '',
    );
    return `${/^[0-9]/.test(camel) ? `_${camel}` : camel}_${language}`;
  };

  const slugs = existsSync(contentDirectory)
    ? readdirSync(contentDirectory)
        .filter((entry) => statSync(join(contentDirectory, entry)).isDirectory())
        .sort()
    : [];

  let imports = '';
  let entries = '';

  for (const slug of slugs) {
    const languageFiles = readdirSync(join(contentDirectory, slug))
      .filter((file) => file.endsWith('.json'))
      .sort();
    if (languageFiles.length === 0) continue;

    const languageLines = languageFiles
      .map((file) => {
        const language = basename(file, '.json');
        const importName = toImportName(slug, language);
        imports += `import ${importName} from '../content/${slug}/${file}';\n`;
        return `      { language: '${language}', story: ${importName} },`;
      })
      .join('\n');

    entries += `  {
    slug: '${slug}',
    languages: [
${languageLines}
    ],
  },
`;
  }

  writeFileSync(
    outputFile,
    `// This file is auto-generated by generate-indexes.ts
// Do not modify this file directly.
import type { ExampleStoryEntry } from '../types';

${imports}
export const exampleStoryRegistry: ExampleStoryEntry[] = [
${entries.trimEnd()}
];
`,
  );
  console.log(
    `Example stories registry generated successfully at: ${outputFile} (${slugs.length} example stor${slugs.length === 1 ? 'y' : 'ies'})`,
  );
}
