import { existsSync, mkdirSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

/**
 * Writes the index of a content folder shaped as `<slug>/<lang>.json`.
 *
 * The same reason as the migrations index: Metro needs a static `import`, so the folder scan happens
 * here, before the build, and not on the device.
 *
 * Two catalogues have this shape - the example stories and the shipped packs - and they are the
 * same problem twice: a folder per item, a file per language, one generated file with one `import`
 * per file found. The parts that differ are names, so they are arguments.
 */
export interface LanguageContentIndexOptions {
  contentDir: string;
  outputFile: string;
  /** The exported constant's name, e.g. `exampleStoryRegistry`. */
  registryName: string;
  /** The entry type's name, e.g. `ExampleStoryEntry`. */
  typeName: string;
  /** The `import type` line that brings `typeName` into the generated file. */
  typeImport: string;
  /** The property each language entry carries the payload under, e.g. `story` or `pack`. */
  payloadProperty: string;
  /**
   * Optional expression used for the imported payload.  This lets a catalogue keep old content
   * readable when a newly exported optional collection becomes part of the package contract.
   */
  formatPayload?: (importName: string) => string;
  /** What to print when done, given how many items were indexed. */
  describe: (count: number) => string;
}

export function generateLanguageContentIndex(options: LanguageContentIndexOptions): void {
  const { contentDir, outputFile } = options;

  mkdirSync(join(outputFile, '..'), { recursive: true });

  const toImportName = (slug: string, language: string) => {
    const camel = slug.replace(/[^a-zA-Z0-9]+(.)?/g, (_, char: string | undefined) =>
      char ? char.toUpperCase() : '',
    );
    return `${/^[0-9]/.test(camel) ? `_${camel}` : camel}_${language}`;
  };

  const slugs = existsSync(contentDir)
    ? readdirSync(contentDir)
        .filter((entry) => statSync(join(contentDir, entry)).isDirectory())
        .sort()
    : [];

  let imports = '';
  let entries = '';

  for (const slug of slugs) {
    const languageFiles = readdirSync(join(contentDir, slug))
      .filter((file) => file.endsWith('.json'))
      .sort();
    if (languageFiles.length === 0) continue;

    const languageLines = languageFiles
      .map((file) => {
        const language = basename(file, '.json');
        const importName = toImportName(slug, language);
        imports += `import ${importName} from '../content/${slug}/${file}';\n`;
        const payload = options.formatPayload?.(importName) ?? importName;
        return `      { language: '${language}', ${options.payloadProperty}: ${payload} },`;
      })
      .join('\n');

    entries += `  {
    slug: '${slug}',
    languages: [
${languageLines}
    ],
  },
`;
  }

  writeFileSync(
    outputFile,
    `// This file is auto-generated by generate-indexes.ts
// Do not modify this file directly.
${options.typeImport}

${imports}
export const ${options.registryName}: ${options.typeName}[] = [
${entries.trimEnd()}
];
`,
  );
  console.log(`${options.describe(slugs.length)} at: ${outputFile}`);
}
