import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';

/**
 * Converte cada migração SQL do drizzle-kit num módulo TypeScript e escreve o índice.
 *
 * O Metro só empacota o que está importado estaticamente: no dispositivo não existe pasta para
 * listar em tempo de execução. Por isso o SQL vira `.ts` e o índice nasce aqui, antes do build.
 */
export function generateMigrationsIndex(clientRoot: string): void {
  const drizzleDirectory = join(clientRoot, 'drizzle');
  const migrationsDirectory = join(clientRoot, 'src/db/migrations');
  const outputFile = join(migrationsDirectory, 'index.ts');

  console.log('Generating migrations index and converting SQL to TS...');
  mkdirSync(migrationsDirectory, { recursive: true });

  const sqlFiles = readdirSync(drizzleDirectory)
    .filter((file) => file.endsWith('.sql'))
    .sort();

  let imports = '';
  let migrationArray = '';

  sqlFiles.forEach((file, index) => {
    const name = basename(file, '.sql');
    const sql = readFileSync(join(drizzleDirectory, file), 'utf8');

    writeFileSync(
      join(migrationsDirectory, `${name}.ts`),
      `import type { SQLiteDatabase } from 'expo-sqlite';

export default async function (db: SQLiteDatabase) {
  await db.execAsync(\`
  ${sql.replace(/`/g, '"')}
\`);
}
`,
    );

    imports += `import migration_${index + 1} from './${name}';\n`;
    migrationArray += `  { id: ${index + 1}, name: '${name}', run: migration_${index + 1} },\n`;
  });

  writeFileSync(
    outputFile,
    `// This file is auto-generated by generate-indexes.ts
// Do not modify this file directly.

${imports}
const migrations = [
  ${migrationArray.trim()}
];

export default migrations;
`,
  );
  console.log('Migrations index generated successfully at:', outputFile);
}
