const coverageThresholds = require('../../scripts/coverage-thresholds.json');

module.exports = {
  preset: 'jest-expo',
  // `src` is here only so *coverage* can see the files no test imports.
  // With only `test/` on the list, Jest does not scan `src/` and the `collectCoverageFrom` below has
  // no effect: the report measures only what the tests already touch, which makes coverage look
  // much bigger than it is (it was 136 out of 377 files, 42% instead of 15%).
  roots: ['<rootDir>/test', '<rootDir>/src'],
  // Deliberately anchored at `test/`: `roots` now includes `src`, and a loose glob would start
  // looking for tests in there too.
  testMatch: ['<rootDir>/test/**/*.test.ts', '<rootDir>/test/**/*.test.tsx'],
  setupFilesAfterEnv: ['<rootDir>/test/jest.setup.ts'],
  collectCoverageFrom: [
    'src/**/*.{ts,tsx}',
    '!src/**/*.d.ts',
    // Generated by scripts/generate-*.js; covering them only distorts the number.
    '!src/db/migrations/**',
    '!src/exampleStories/**',
  ],
  coverageReporters: ['text', 'lcov'],
  // A floor, not a target: set a little below what was measured so as to absorb fluctuation, and to rise
  // along when coverage rises. See the ratchet rule in TESTING_PLAN.md.
  coverageThreshold: {
    global: coverageThresholds.client,
  },
};
