import { cookie } from '@elysiajs/cookie';
import { cors } from '@elysiajs/cors';
import { jwt } from '@elysiajs/jwt';
import { staticPlugin } from '@elysiajs/static';
import { Elysia, t } from 'elysia';
import { existsSync, readFileSync } from 'fs';
import * as path from 'path';
import {
  adminDistPath as resolveAdminDistPath,
  clientDistPath as resolveClientDistPath,
  desktopIconPath,
  showcaseDistPath as resolveShowcaseDistPath,
} from './config/resourceRoot';
import {
  CLIENT_APP_ISOLATION_HEADERS,
  isClientDistRootAssetPath,
  isShowcasePath,
  readClientDistRootAsset,
  readHostedClientFile,
  SHOWCASE_PATH_PREFIX,
} from './services/hostedClient';
import { env } from './config/env';
import { createApiRoutes, isApiOrLegacyApiPath } from './api';
import { showcaseSettingsService } from './services/ShowcaseSettingsService';
import { AppError } from './utils/errors';
import { logger } from './utils/logger';

/**
 * Co-hospedagem do painel admin: subir a API já serve o app web junto, no mesmo
 * processo/porta, sem precisar de um segundo deploy. `apps/admin` continua sendo buildado
 * separadamente (`bun run build`, que roda `vite build` - ver apps/admin/package.json); o
 * que muda aqui é só servir o resultado estático.
 *
 * O prefixo do app é `/admin` (arquivos estáticos + fallback de SPA abaixo); a API JSON
 * usada por ele mora em `/api/admin/*`, para as duas coisas não brigarem pelo mesmo espaço
 * de URL. Se o build ainda não existir (dev sem `bun run build`, ou API rodando sozinha),
 * isso não derruba o servidor - só o painel fica indisponível, a API continua normal.
 *
 * Resolvido por `resourceRoot` (não `process.cwd()`): no checkout aponta a `apps/admin/dist`;
 * no zip do Keres Server, a `admin-dist` ao lado do executável.
 */
const adminDistPath = resolveAdminDistPath();
const adminDistIndexPath = path.join(adminDistPath, 'index.html');
const adminUiAvailable = existsSync(adminDistIndexPath);
/** Generated by the admin Vite build from desktop_icon.png (png-to-ico). */
const adminFaviconPath = path.join(adminDistPath, 'favicon.ico');
/**
 * O site público (Showcase) é a *segunda* saída de build de `apps/admin` - mesmo projeto,
 * outra entrada (`showcase.html`, `vite.showcase.config.ts`). Os arquivos estáticos moram sob
 * `/_showcase/` (o `base` do Vite) e as *páginas* moram na raiz: montar o estático direto em
 * `/` faria ele sombrear as rotas da API. Ver o catch-all no fim do arquivo.
 */
const showcaseDistPath = resolveShowcaseDistPath();
const showcaseDistIndexPath = path.join(showcaseDistPath, 'index.html');
const showcaseUiAvailable = existsSync(showcaseDistIndexPath);
/** O mesmo .ico, gerado do mesmo PNG, pelo build do site público. */
const showcaseFaviconPath = path.join(showcaseDistPath, 'favicon.ico');
const clientDistPath = resolveClientDistPath();
const clientDistIndexPath = path.join(clientDistPath, 'index.html');
const clientUiAvailable = existsSync(clientDistIndexPath);

/** Fallback before an admin build exists — same PNG desktop uses, not copied into admin. */
const desktopIconFilePath = desktopIconPath();

/** Headers for the co-hosted admin SPA (static assets + HTML fallback). Not applied to `/api/admin/*`. */
const ADMIN_UI_SECURITY_HEADERS: Record<string, string> = {
  'Content-Security-Policy':
    "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'no-referrer',
  'X-Frame-Options': 'DENY',
};

const SERVER_LANDING_SECURITY_HEADERS: Record<string, string> = {
  'Content-Security-Policy':
    "default-src 'self'; style-src 'unsafe-inline'; img-src 'self' data:; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'no-referrer',
  'X-Frame-Options': 'DENY',
};

function applyAdminUiSecurityHeaders(set: { headers: Record<string, string | number> }): void {
  for (const [name, value] of Object.entries(ADMIN_UI_SECURITY_HEADERS)) {
    set.headers[name] = value;
  }
}

function applyServerLandingSecurityHeaders(set: {
  headers: Record<string, string | number>;
}): void {
  for (const [name, value] of Object.entries(SERVER_LANDING_SECURITY_HEADERS)) {
    set.headers[name] = value;
  }
}

/** Página deliberadamente estática: o servidor continua útil sem expor o cliente hospedado. */
function serverLandingHtml(): string {
  return `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Keres Server</title><style>
body{margin:0;min-height:100vh;display:grid;place-items:center;background:#121212;color:#fff;font-family:system-ui,sans-serif}
main{width:min(34rem,calc(100% - 3rem));padding:2.5rem;border:1px solid #333;border-radius:1rem;background:#1e1e1e;text-align:center}
h1{margin:0 0 .75rem;color:#bb86fc}p{margin:0 0 2rem;color:#d0c8d8;line-height:1.55}.actions{display:flex;gap:.75rem;justify-content:center;flex-wrap:wrap}a{padding:.7rem 1rem;border-radius:.55rem;background:#bb86fc;color:#1b1024;text-decoration:none;font-weight:700}a.secondary{background:transparent;color:#eaddff;border:1px solid #bb86fc}
</style></head><body><main><h1>Keres Server</h1><p>Este endereço hospeda um servidor Keres.</p><div class="actions"><a href="/admin">Administração</a><a class="secondary" href="/showcase">Vitrine</a></div></main></body></html>`;
}

function applyClientAppIsolationHeaders(set: { headers: Record<string, string | number> }): void {
  for (const [name, value] of Object.entries(CLIENT_APP_ISOLATION_HEADERS)) {
    set.headers[name] = value;
  }
}

function isClientAppPath(pathname: string): boolean {
  return pathname === '/' || isClientDistRootAssetPath(pathname);
}

function serveClientRootAsset(
  set: { status?: number | string; headers: Record<string, string | number> },
  request: Request,
): Uint8Array | { message: string } {
  if (!clientUiAvailable) {
    set.status = 404;
    return { message: 'Not found' };
  }
  const file = readClientDistRootAsset(clientDistPath, new URL(request.url).pathname);
  if (!file) {
    set.status = 404;
    return { message: 'Not found' };
  }
  applyClientAppIsolationHeaders(set);
  set.headers['content-type'] = file.contentType;
  return file.body;
}

if (!showcaseUiAvailable) {
  logger.warn(
    `Showcase UI not built - the public site will be unavailable. Run 'bun run admin:build' to enable it.`,
  );
}

if (!adminUiAvailable) {
  logger.warn(
    `Admin UI not built - /admin will 404. Run 'bun run build' in apps/api (or apps/admin) to enable it.`,
  );
}

if (!clientUiAvailable) {
  logger.warn(
    `Hosted client not built - / will not serve the web app. Run 'bun run client:build' to enable it.`,
  );
}

/** pg/network error codes that mean "couldn't reach or lost the database", not an app bug. */
const DB_CONNECTIVITY_ERROR_CODES = new Set([
  'ECONNREFUSED',
  'ENOTFOUND',
  'ETIMEDOUT',
  'EHOSTUNREACH',
  'ENETUNREACH',
  'EAI_AGAIN',
  '57P03', // Postgres: cannot_connect_now
]);

export function isDatabaseConnectivityError(error: unknown): boolean {
  let current: unknown = error;
  // drizzle/pg wrap the root network error in `.cause`, sometimes more than one layer deep.
  for (let depth = 0; current && depth < 5; depth++) {
    const code = (current as { code?: unknown }).code;
    if (typeof code === 'string' && DB_CONNECTIVITY_ERROR_CODES.has(code)) {
      return true;
    }
    current = (current as { cause?: unknown }).cause;
  }
  return false;
}

// Define a placeholder type for the JWT payload
// In a real application, this would be derived from your User entity
export interface JWTPayload {
  userId: string;
  username: string;
}

/** Cria a aplicação sem migrar banco, reconciliar admin ou abrir uma porta. */
export async function createApp() {
  return (
    new Elysia()
      .use(cookie())
      .use(
        jwt({
          name: 'jwt',
          secret: env.JWT_SECRET,
          exp: '1h', // Access token expiration
          schema: t.Object({
            // Define schema for JWT payload
            userId: t.String(),
            username: t.String(),
          }),
        }),
      )
      .use(
        cors({
          // No client (mobile, desktop, web export, admin panel) authenticates via cookies -
          // every one of them attaches `Authorization: Bearer <token>` itself (see apiClient.ts
          // on the client and admin sides), so nothing actually needs the browser to send
          // cookies cross-origin. The default `credentials: true` combined with the default
          // `origin: true` (reflects any request Origin back) let any third-party site make
          // credentialed requests using this app's httpOnly auth cookies and read the response.
          // Disabling credentials here closes that off while keeping `origin: true`, which this
          // self-hosted, multi-deployment app still needs (there's no fixed set of client
          // origins to allowlist - every self-hoster's install is its own origin).
          credentials: false,
        }),
      )
      .derive(async ({ jwt, headers, cookie }) => {
        let token: string | null | undefined = headers['authorization']?.startsWith('Bearer ')
          ? headers['authorization'].slice(7)
          : null;

        if (!token && typeof cookie['access_token'].value === 'string') {
          token = cookie['access_token'].value;
        }

        if (!token) {
          // If no token, user is not authenticated.
          // We don't throw an error here, but rather return null for the user,
          // allowing routes to decide if authentication is mandatory.
          return { user: null };
        }

        // An invalid/expired token is treated exactly like no token at all - this `.derive()`
        // runs on every request, including public ones (GET /api/kerescheck, GET /api/swagger, POST
        // /auth/login...). Throwing 401 here used to reject those too, just because a client
        // happened to carry a stale token; each route that actually requires auth already does
        // its own `if (!user) { 401 }` check right after this runs, so nothing is lost by
        // deferring the rejection to there instead.
        try {
          const payload = await jwt.verify(token);
          return { user: (payload || null) as JWTPayload | null };
        } catch {
          return { user: null };
        }
      })
      .onError(({ code, error, set, path, request, user, params }) => {
        const err = error instanceof Error ? error : new Error(String(error));
        const label = `${request.method} ${path}`;
        const userId = (user as JWTPayload | null)?.userId ?? null;
        // Só rotas com um :storyId nos params carregam isto - não força o campo quando não é
        // significativo (ex: nem toda rota é escopada a uma história).
        const storyId = (params as { storyId?: string } | undefined)?.storyId ?? null;

        // A route that deliberately rejected with AppError (any status, including 500)
        // already chose a safe, user-facing message - relay it as-is.
        if (err instanceof AppError) {
          set.status = err.status;
          logger.warn(`Rejected request: ${label}`, {
            status: err.status,
            message: err.message,
            userId,
            storyId,
          });
          return { message: err.message };
        }

        // Route handlers that deliberately picked a non-500 status before throwing a plain
        // Error (401/403/404/409...) already chose a safe message too - relay it as-is.
        // 500 is excluded here because Elysia defaults untouched status to 500 for any
        // unclassified thrown error, so it can't tell "the app chose 500" from "nothing did".
        if (typeof set.status === 'number' && set.status !== 500) {
          logger.warn(`Rejected request: ${label}`, {
            status: set.status,
            message: err.message,
            userId,
            storyId,
          });
          return { message: err.message };
        }

        if (isDatabaseConnectivityError(err)) {
          set.status = 503;
          logger.error(`Database unreachable while handling ${label}`, err, {
            code,
            userId,
            storyId,
          });
          return { message: 'Service temporarily unavailable. Please try again shortly.' };
        }

        // Anything else is unexpected - never leak internals (SQL, stack traces) to the client.
        set.status = 500;
        logger.error(`Unhandled error while handling ${label}`, err, { code, userId, storyId });
        return { message: 'Internal server error.' };
      })
      .get(
        '/',
        async ({ set }) => {
          // A raiz é o cliente web (mesmo export que o Electron), para o Expo Router viver
          // em `/` como no desktop. O administrador pode trocar isso por uma landing mínima.
          // A raiz sempre serviu o cliente sem depender do banco. Preservar esse caminho quando
          // o banco ainda está iniciando ou caiu evita trocar uma página útil por um 503; o
          // default da configuração também é "ligado".
          const hostedClientEnabled = await showcaseSettingsService
            .isHostedClientEnabled()
            .catch(() => true);
          if (clientUiAvailable && hostedClientEnabled) {
            const file = readHostedClientFile(clientDistPath, '/');
            if (file) {
              applyClientAppIsolationHeaders(set);
              set.headers['content-type'] = file.contentType;
              return file.body;
            }
          }
          if (!hostedClientEnabled) {
            applyServerLandingSecurityHeaders(set);
            set.headers['content-type'] = 'text/html; charset=utf-8';
            return serverLandingHtml();
          }
          if (showcaseUiAvailable && (await showcaseSettingsService.isEnabled())) {
            set.status = 302;
            set.headers.location = SHOWCASE_PATH_PREFIX;
            return;
          }
          set.status = 302;
          set.headers.location = '/api/swagger';
          return;
        },
        {
          detail: {
            summary: 'Hosted Keres client (or showcase / Swagger)',
            description:
              'Serves the web export of apps/client at the origin root, with COOP/COEP so expo-sqlite can use SharedArrayBuffer. Falls back to /showcase or /api/swagger when the export is missing.',
            tags: ['Client'],
          },
        },
      )
      .get(
        '/favicon.ico',
        ({ set }) => {
          // Painel e site público geram o mesmo .ico, do mesmo PNG - qualquer um dos dois
          // serve. Procurar nos dois evita que a aba fique sem ícone num servidor que só
          // buildou o site (ou só o painel); o PNG do cliente é o último recurso, para quando
          // nenhum build existe ainda.
          const generatedIcoPath = [adminFaviconPath, showcaseFaviconPath].find((candidate) =>
            existsSync(candidate),
          );
          const filePath = generatedIcoPath ?? desktopIconFilePath;
          const useGeneratedIco = !!generatedIcoPath;
          if (!existsSync(filePath)) {
            set.status = 404;
            return { message: 'Not found' };
          }
          set.headers['content-type'] = useGeneratedIco ? 'image/x-icon' : 'image/png';
          set.headers['cache-control'] = 'public, max-age=86400';
          // `readFileSync` instead of `Bun.file`: this route is hit by the Node/Vitest suite
          // (`kerescheck.test.ts`) as well as Bun in production. The file is a few KB.
          return new Uint8Array(readFileSync(filePath));
        },
        {
          detail: {
            summary: 'Favicon',
            description:
              'Serves the ICO generated at web build time from apps/client desktop_icon.png (same source as apps/desktop).',
            tags: ['Admin'],
          },
        },
      )
      .use(createApiRoutes())
      .onAfterHandle(({ request, set }) => {
        const pathname = new URL(request.url).pathname;
        if (isClientAppPath(pathname)) {
          applyClientAppIsolationHeaders(set);
          return;
        }
        if (pathname.startsWith('/admin')) {
          applyAdminUiSecurityHeaders(set);
        }
        if (isShowcasePath(pathname) || pathname.startsWith('/_showcase')) {
          applyAdminUiSecurityHeaders(set);
        }
      })
      // Sem compatibilidade: antes de o fallback do painel poder devolver seu HTML, os antigos
      // endpoints administrativos recebem o mesmo 404 JSON de qualquer rota API removida.
      .all('/admin/api', ({ set }) => {
        set.status = 404;
        return { message: 'Not found' };
      })
      .all('/admin/api/*', ({ set }) => {
        set.status = 404;
        return { message: 'Not found' };
      })
      .use(
        adminUiAvailable
          ? await staticPlugin({ assets: adminDistPath, prefix: '/admin', alwaysStatic: true })
          : new Elysia(),
      )
      .get(
        '/admin/*',
        ({ set, path: requestPath }) => {
          // `staticPlugin` e o fallback de SPA são ambos compilados pelo Elysia; para caminhos
          // que parecem uma rota do painel, o fallback tem precedência sobre `.all()` acima.
          // Não permita que o contrato removido `/admin/api/*` vire um 200 com index.html.
          if (requestPath === '/admin/api' || requestPath.startsWith('/admin/api/')) {
            set.status = 404;
            return { message: 'Not found' };
          }
          if (!adminUiAvailable) {
            set.status = 404;
            return { message: "Admin UI not built. Run 'bun run build' in apps/api first." };
          }
          applyAdminUiSecurityHeaders(set);
          // Fallback de SPA: qualquer rota do painel que não seja um arquivo estático real (ex:
          // /admin/users, uma rota de cliente do React Router) recebe o mesmo index.html, que
          // então resolve a rota no navegador. Sem isto, um F5 em /admin/users daria 404.
          // Node/Vitest has no `Bun.file`; the HTML is tiny so a sync read is fine.
          set.headers['content-type'] = 'text/html; charset=utf-8';
          return readFileSync(adminDistIndexPath, 'utf8');
        },
        {
          detail: {
            summary: 'Admin panel (single-page app)',
            description: 'Serves the built apps/admin SPA and its client-side routes.',
            tags: ['Admin'],
          },
        },
      )
      .get(
        '/app',
        ({ set }) => {
          set.status = 302;
          set.headers.location = '/';
        },
        {
          detail: {
            summary: 'Legacy hosted-client path',
            description: 'The web client used to live at /app; it now occupies the origin root.',
            tags: ['Client'],
          },
        },
      )
      .get(
        '/app/*',
        ({ set }) => {
          set.status = 302;
          set.headers.location = '/';
        },
        {
          detail: {
            summary: 'Legacy hosted-client path',
            tags: ['Client'],
          },
        },
      )
      .get(
        '/showcase',
        async ({ set }) => {
          if (!showcaseUiAvailable || !(await showcaseSettingsService.isEnabled())) {
            set.status = 404;
            return { message: 'Not found' };
          }
          applyAdminUiSecurityHeaders(set);
          set.headers['content-type'] = 'text/html; charset=utf-8';
          return readFileSync(showcaseDistIndexPath, 'utf8');
        },
        {
          detail: {
            summary: 'Public showcase',
            description: 'Lists stories published on this server.',
            tags: ['Showcase'],
          },
        },
      )
      .get(
        '/showcase/*',
        async ({ set }) => {
          if (!showcaseUiAvailable || !(await showcaseSettingsService.isEnabled())) {
            set.status = 404;
            return { message: 'Not found' };
          }
          applyAdminUiSecurityHeaders(set);
          set.headers['content-type'] = 'text/html; charset=utf-8';
          return readFileSync(showcaseDistIndexPath, 'utf8');
        },
        {
          detail: {
            summary: 'Public showcase (SPA fallback)',
            tags: ['Showcase'],
          },
        },
      )
      .get('/_expo/*', ({ set, request }) => serveClientRootAsset(set, request), {
        detail: {
          summary: 'Expo web runtime (worker and bundles requested from origin root)',
          tags: ['Client'],
        },
      })
      .get('/assets/*', ({ set, request }) => serveClientRootAsset(set, request), {
        detail: {
          summary: 'Expo web static assets requested from origin root',
          tags: ['Client'],
        },
      })
      .use(
        showcaseUiAvailable
          ? await staticPlugin({
              assets: showcaseDistPath,
              prefix: '/_showcase',
              alwaysStatic: true,
            })
          : new Elysia(),
      )
      // Expo Router só reconhece `/`. Um F5 em `/StorySelection` (ou o que o React Navigation
      // tiver escrito na barra) tem de voltar à raiz, não servir o index nesse path — senão o
      // Router mostra unmatched. API e /showcase já foram registados acima.
      .get(
        '/*',
        ({ set, path: requestPath }) => {
          if (isApiOrLegacyApiPath(requestPath)) {
            set.status = 404;
            return { message: 'Not found' };
          }
          if (clientUiAvailable) {
            set.status = 302;
            set.headers.location = '/';
            return;
          }
          set.status = 404;
          return { message: 'Not found' };
        },
        {
          detail: {
            summary: 'Refresh fallback to the hosted client',
            description:
              'Unknown non-API paths redirect to / so a refresh never lands on an Expo Router unmatched screen.',
            tags: ['Client'],
          },
        },
      )
  );
}
