import { cookie } from '@elysiajs/cookie';
import { cors } from '@elysiajs/cors';
import { jwt } from '@elysiajs/jwt';
import { staticPlugin } from '@elysiajs/static';
import { Elysia, t } from 'elysia';
import { existsSync, readFileSync } from 'fs';
import * as path from 'path';
import {
  adminDistPath as resolveAdminDistPath,
  clientDistPath as resolveClientDistPath,
  desktopIconPath,
  showcaseDistPath as resolveShowcaseDistPath,
} from './config/resourceRoot';
import {
  CLIENT_APP_ISOLATION_HEADERS,
  isClientDistRootAssetPath,
  isShowcasePath,
  readClientDistRootAsset,
  readHostedClientFile,
  SHOWCASE_PATH_PREFIX,
} from './services/hostedClient';
import { env } from './config/env';
import { createApiRoutes, isApiOrLegacyApiPath } from './api';
import { showcaseSettingsService } from './services/ShowcaseSettingsService';
import { AppError } from './utils/errors';
import { logger } from './utils/logger';

/**
 * Co-hosting the admin panel: bringing the API up already serves the web app alongside it, in the
 * same process and port, with no need for a second deploy. `apps/admin` is still built separately
 * (`bun run build`, which runs `vite build` - see apps/admin/package.json); what changes here is only
 * serving the static result.
 *
 * The app's prefix is `/admin` (static files + the SPA fallback below); the JSON API it uses lives at
 * `/api/admin/*`, so the two do not fight over the same URL space. If the build does not exist yet
 * (dev without `bun run build`, or the API running on its own), that does not take the server down -
 * only the panel is unavailable, the API carries on as usual.
 *
 * Resolved by `resourceRoot` (not `process.cwd()`): in the checkout it points at `apps/admin/dist`;
 * in the Keres Server zip, at the `admin-dist` next to the executable.
 */
const adminDistPath = resolveAdminDistPath();
const adminDistIndexPath = path.join(adminDistPath, 'index.html');
const adminUiAvailable = existsSync(adminDistIndexPath);
/** Generated by the admin Vite build from desktop_icon.png (png-to-ico). */
const adminFaviconPath = path.join(adminDistPath, 'favicon.ico');
/**
 * The public site (Showcase) is `apps/admin`'s *second* build output - same project, another entry
 * point (`showcase.html`, `vite.showcase.config.ts`). The static files live under `/_showcase/`
 * (Vite's `base`) and the *pages* live at the root: mounting the static files directly at `/` would
 * make them shadow the API routes. See the catch-all at the end of the file.
 */
const showcaseDistPath = resolveShowcaseDistPath();
const showcaseDistIndexPath = path.join(showcaseDistPath, 'index.html');
const showcaseUiAvailable = existsSync(showcaseDistIndexPath);
/** The same .ico, generated from the same PNG, by the public site's build. */
const showcaseFaviconPath = path.join(showcaseDistPath, 'favicon.ico');
const clientDistPath = resolveClientDistPath();
const clientDistIndexPath = path.join(clientDistPath, 'index.html');
const clientUiAvailable = existsSync(clientDistIndexPath);

/** Fallback before an admin build exists — same PNG desktop uses, not copied into admin. */
const desktopIconFilePath = desktopIconPath();

/** Headers for the co-hosted admin SPA (static assets + HTML fallback). Not applied to `/api/admin/*`. */
const ADMIN_UI_SECURITY_HEADERS: Record<string, string> = {
  'Content-Security-Policy':
    "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'no-referrer',
  'X-Frame-Options': 'DENY',
};

const SERVER_LANDING_SECURITY_HEADERS: Record<string, string> = {
  'Content-Security-Policy':
    "default-src 'self'; style-src 'unsafe-inline'; img-src 'self' data:; base-uri 'none'; form-action 'none'; frame-ancestors 'none'",
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'no-referrer',
  'X-Frame-Options': 'DENY',
};

function applyAdminUiSecurityHeaders(set: { headers: Record<string, string | number> }): void {
  for (const [name, value] of Object.entries(ADMIN_UI_SECURITY_HEADERS)) {
    set.headers[name] = value;
  }
}

function applyServerLandingSecurityHeaders(set: {
  headers: Record<string, string | number>;
}): void {
  for (const [name, value] of Object.entries(SERVER_LANDING_SECURITY_HEADERS)) {
    set.headers[name] = value;
  }
}

/** A deliberately static page: the server stays useful without exposing the hosted client. */
function serverLandingHtml(): string {
  return `<!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Keres Server</title><style>
body{margin:0;min-height:100vh;display:grid;place-items:center;background:#121212;color:#fff;font-family:system-ui,sans-serif}
main{width:min(34rem,calc(100% - 3rem));padding:2.5rem;border:1px solid #333;border-radius:1rem;background:#1e1e1e;text-align:center}
h1{margin:0 0 .75rem;color:#bb86fc}p{margin:0 0 2rem;color:#d0c8d8;line-height:1.55}.actions{display:flex;gap:.75rem;justify-content:center;flex-wrap:wrap}a{padding:.7rem 1rem;border-radius:.55rem;background:#bb86fc;color:#1b1024;text-decoration:none;font-weight:700}a.secondary{background:transparent;color:#eaddff;border:1px solid #bb86fc}
</style></head><body><main><h1>Keres Server</h1><p>Este endereço hospeda um servidor Keres.</p><div class="actions"><a href="/admin">Administração</a><a class="secondary" href="/showcase">Vitrine</a></div></main></body></html>`;
}

function applyClientAppIsolationHeaders(set: { headers: Record<string, string | number> }): void {
  for (const [name, value] of Object.entries(CLIENT_APP_ISOLATION_HEADERS)) {
    set.headers[name] = value;
  }
}

function isClientAppPath(pathname: string): boolean {
  return pathname === '/' || isClientDistRootAssetPath(pathname);
}

function serveClientRootAsset(
  set: { status?: number | string; headers: Record<string, string | number> },
  request: Request,
): Uint8Array | { message: string } {
  if (!clientUiAvailable) {
    set.status = 404;
    return { message: 'Not found' };
  }
  const file = readClientDistRootAsset(clientDistPath, new URL(request.url).pathname);
  if (!file) {
    set.status = 404;
    return { message: 'Not found' };
  }
  applyClientAppIsolationHeaders(set);
  set.headers['content-type'] = file.contentType;
  return file.body;
}

if (!showcaseUiAvailable) {
  logger.warn(
    `Showcase UI not built - the public site will be unavailable. Run 'bun run admin:build' to enable it.`,
  );
}

if (!adminUiAvailable) {
  logger.warn(
    `Admin UI not built - /admin will 404. Run 'bun run build' in apps/api (or apps/admin) to enable it.`,
  );
}

if (!clientUiAvailable) {
  logger.warn(
    `Hosted client not built - / will not serve the web app. Run 'bun run client:build' to enable it.`,
  );
}

/** pg/network error codes that mean "couldn't reach or lost the database", not an app bug. */
const DB_CONNECTIVITY_ERROR_CODES = new Set([
  'ECONNREFUSED',
  'ENOTFOUND',
  'ETIMEDOUT',
  'EHOSTUNREACH',
  'ENETUNREACH',
  'EAI_AGAIN',
  '57P03', // Postgres: cannot_connect_now
]);

export function isDatabaseConnectivityError(error: unknown): boolean {
  let current: unknown = error;
  // drizzle/pg wrap the root network error in `.cause`, sometimes more than one layer deep.
  for (let depth = 0; current && depth < 5; depth++) {
    const code = (current as { code?: unknown }).code;
    if (typeof code === 'string' && DB_CONNECTIVITY_ERROR_CODES.has(code)) {
      return true;
    }
    current = (current as { cause?: unknown }).cause;
  }
  return false;
}

// Define a placeholder type for the JWT payload
// In a real application, this would be derived from your User entity
export interface JWTPayload {
  userId: string;
  username: string;
}

/** Creates the application without migrating the database, reconciling the admin or opening a port. */
export async function createApp() {
  return (
    new Elysia()
      .use(cookie())
      .use(
        jwt({
          name: 'jwt',
          secret: env.JWT_SECRET,
          exp: '1h', // Access token expiration
          schema: t.Object({
            // Define schema for JWT payload
            userId: t.String(),
            username: t.String(),
          }),
        }),
      )
      .use(
        cors({
          // No client (mobile, desktop, web export, admin panel) authenticates via cookies -
          // every one of them attaches `Authorization: Bearer <token>` itself (see apiClient.ts
          // on the client and admin sides), so nothing actually needs the browser to send
          // cookies cross-origin. The default `credentials: true` combined with the default
          // `origin: true` (reflects any request Origin back) let any third-party site make
          // credentialed requests using this app's httpOnly auth cookies and read the response.
          // Disabling credentials here closes that off while keeping `origin: true`, which this
          // self-hosted, multi-deployment app still needs (there's no fixed set of client
          // origins to allowlist - every self-hoster's install is its own origin).
          credentials: false,
        }),
      )
      .derive(async ({ jwt, headers, cookie }) => {
        let token: string | null | undefined = headers['authorization']?.startsWith('Bearer ')
          ? headers['authorization'].slice(7)
          : null;

        if (!token && typeof cookie['access_token'].value === 'string') {
          token = cookie['access_token'].value;
        }

        if (!token) {
          // If no token, user is not authenticated.
          // We don't throw an error here, but rather return null for the user,
          // allowing routes to decide if authentication is mandatory.
          return { user: null };
        }

        // An invalid/expired token is treated exactly like no token at all - this `.derive()`
        // runs on every request, including public ones (GET /api/kerescheck, GET /api/swagger, POST
        // /auth/login...). Throwing 401 here used to reject those too, just because a client
        // happened to carry a stale token; each route that actually requires auth already does
        // its own `if (!user) { 401 }` check right after this runs, so nothing is lost by
        // deferring the rejection to there instead.
        try {
          const payload = await jwt.verify(token);
          return { user: (payload || null) as JWTPayload | null };
        } catch {
          return { user: null };
        }
      })
      .onError(({ code, error, set, path, request, user, params }) => {
        const err = error instanceof Error ? error : new Error(String(error));
        const label = `${request.method} ${path}`;
        const userId = (user as JWTPayload | null)?.userId ?? null;
        // Only routes with a :storyId in their params carry this - it does not force the field where it is
        // not meaningful (not every route is scoped to a story).
        const storyId = (params as { storyId?: string } | undefined)?.storyId ?? null;

        // A route that deliberately rejected with AppError (any status, including 500)
        // already chose a safe, user-facing message - relay it as-is.
        if (err instanceof AppError) {
          set.status = err.status;
          logger.warn(`Rejected request: ${label}`, {
            status: err.status,
            message: err.message,
            userId,
            storyId,
          });
          return { message: err.message };
        }

        // Route handlers that deliberately picked a non-500 status before throwing a plain
        // Error (401/403/404/409...) already chose a safe message too - relay it as-is.
        // 500 is excluded here because Elysia defaults untouched status to 500 for any
        // unclassified thrown error, so it can't tell "the app chose 500" from "nothing did".
        if (typeof set.status === 'number' && set.status !== 500) {
          logger.warn(`Rejected request: ${label}`, {
            status: set.status,
            message: err.message,
            userId,
            storyId,
          });
          return { message: err.message };
        }

        if (isDatabaseConnectivityError(err)) {
          set.status = 503;
          logger.error(`Database unreachable while handling ${label}`, err, {
            code,
            userId,
            storyId,
          });
          return { message: 'Service temporarily unavailable. Please try again shortly.' };
        }

        // Anything else is unexpected - never leak internals (SQL, stack traces) to the client.
        set.status = 500;
        logger.error(`Unhandled error while handling ${label}`, err, { code, userId, storyId });
        return { message: 'Internal server error.' };
      })
      .get(
        '/',
        async ({ set }) => {
          // The root is the web client (the same export Electron uses), so Expo Router lives at `/` as it does
          // on the desktop. The administrator can swap that for a minimal landing page. The root has always
          // served the client without depending on the database. Preserving that path while the database is
          // still starting up or is down avoids trading a useful page for a 503; the configuration's default is
          // also "on".
          const hostedClientEnabled = await showcaseSettingsService
            .isHostedClientEnabled()
            .catch(() => true);
          if (clientUiAvailable && hostedClientEnabled) {
            const file = readHostedClientFile(clientDistPath, '/');
            if (file) {
              applyClientAppIsolationHeaders(set);
              set.headers['content-type'] = file.contentType;
              return file.body;
            }
          }
          if (!hostedClientEnabled) {
            applyServerLandingSecurityHeaders(set);
            set.headers['content-type'] = 'text/html; charset=utf-8';
            return serverLandingHtml();
          }
          if (showcaseUiAvailable && (await showcaseSettingsService.isEnabled())) {
            set.status = 302;
            set.headers.location = SHOWCASE_PATH_PREFIX;
            return;
          }
          set.status = 302;
          set.headers.location = '/api/swagger';
          return;
        },
        {
          detail: {
            summary: 'Hosted Keres client (or showcase / Swagger)',
            description:
              'Serves the web export of apps/client at the origin root, with COOP/COEP so expo-sqlite can use SharedArrayBuffer. Falls back to /showcase or /api/swagger when the export is missing.',
            tags: ['Client'],
          },
        },
      )
      .get(
        '/favicon.ico',
        ({ set }) => {
          // The panel and the public site generate the same .ico, from the same PNG - either one works.
          // Looking in both keeps the tab from having no icon on a server that only built the site (or only the
          // panel); the client's PNG is the last resort, for when no build exists yet.
          const generatedIcoPath = [adminFaviconPath, showcaseFaviconPath].find((candidate) =>
            existsSync(candidate),
          );
          const filePath = generatedIcoPath ?? desktopIconFilePath;
          const useGeneratedIco = !!generatedIcoPath;
          if (!existsSync(filePath)) {
            set.status = 404;
            return { message: 'Not found' };
          }
          set.headers['content-type'] = useGeneratedIco ? 'image/x-icon' : 'image/png';
          set.headers['cache-control'] = 'public, max-age=86400';
          // `readFileSync` instead of `Bun.file`: this route is hit by the Node/Vitest suite
          // (`kerescheck.test.ts`) as well as Bun in production. The file is a few KB.
          return new Uint8Array(readFileSync(filePath));
        },
        {
          detail: {
            summary: 'Favicon',
            description:
              'Serves the ICO generated at web build time from apps/client desktop_icon.png (same source as apps/desktop).',
            tags: ['Admin'],
          },
        },
      )
      .use(createApiRoutes())
      .onAfterHandle(({ request, set }) => {
        const pathname = new URL(request.url).pathname;
        if (isClientAppPath(pathname)) {
          applyClientAppIsolationHeaders(set);
          return;
        }
        if (pathname.startsWith('/admin')) {
          applyAdminUiSecurityHeaders(set);
        }
        if (isShowcasePath(pathname) || pathname.startsWith('/_showcase')) {
          applyAdminUiSecurityHeaders(set);
        }
      })
      // Sem compatibilidade: antes de o fallback do painel poder devolver seu HTML, os antigos
      // endpoints administrativos recebem o mesmo 404 JSON de qualquer rota API removida.
      .all('/admin/api', ({ set }) => {
        set.status = 404;
        return { message: 'Not found' };
      })
      .all('/admin/api/*', ({ set }) => {
        set.status = 404;
        return { message: 'Not found' };
      })
      .use(
        adminUiAvailable
          ? await staticPlugin({ assets: adminDistPath, prefix: '/admin', alwaysStatic: true })
          : new Elysia(),
      )
      .get(
        '/admin/*',
        ({ set, path: requestPath }) => {
          // `staticPlugin` and the SPA fallback are both compiled by Elysia; for paths that look like a panel
          // route, the fallback takes precedence over the `.all()` above. Do not let the removed
          // `/admin/api/*` contract become a 200 with index.html.
          if (requestPath === '/admin/api' || requestPath.startsWith('/admin/api/')) {
            set.status = 404;
            return { message: 'Not found' };
          }
          if (!adminUiAvailable) {
            set.status = 404;
            return { message: "Admin UI not built. Run 'bun run build' in apps/api first." };
          }
          applyAdminUiSecurityHeaders(set);
          // SPA fallback: any panel route that is not a real static file (say, /admin/users, a React Router
          // client route) gets the same index.html, which then resolves the route in the browser. Without this,
          // an F5 on /admin/users would give a 404.
          // Node/Vitest has no `Bun.file`; the HTML is tiny so a sync read is fine.
          set.headers['content-type'] = 'text/html; charset=utf-8';
          return readFileSync(adminDistIndexPath, 'utf8');
        },
        {
          detail: {
            summary: 'Admin panel (single-page app)',
            description: 'Serves the built apps/admin SPA and its client-side routes.',
            tags: ['Admin'],
          },
        },
      )
      .get(
        '/app',
        ({ set }) => {
          set.status = 302;
          set.headers.location = '/';
        },
        {
          detail: {
            summary: 'Legacy hosted-client path',
            description: 'The web client used to live at /app; it now occupies the origin root.',
            tags: ['Client'],
          },
        },
      )
      .get(
        '/app/*',
        ({ set }) => {
          set.status = 302;
          set.headers.location = '/';
        },
        {
          detail: {
            summary: 'Legacy hosted-client path',
            tags: ['Client'],
          },
        },
      )
      .get(
        '/showcase',
        async ({ set }) => {
          if (!showcaseUiAvailable || !(await showcaseSettingsService.isEnabled())) {
            set.status = 404;
            return { message: 'Not found' };
          }
          applyAdminUiSecurityHeaders(set);
          set.headers['content-type'] = 'text/html; charset=utf-8';
          return readFileSync(showcaseDistIndexPath, 'utf8');
        },
        {
          detail: {
            summary: 'Public showcase',
            description: 'Lists stories published on this server.',
            tags: ['Showcase'],
          },
        },
      )
      .get(
        '/showcase/*',
        async ({ set }) => {
          if (!showcaseUiAvailable || !(await showcaseSettingsService.isEnabled())) {
            set.status = 404;
            return { message: 'Not found' };
          }
          applyAdminUiSecurityHeaders(set);
          set.headers['content-type'] = 'text/html; charset=utf-8';
          return readFileSync(showcaseDistIndexPath, 'utf8');
        },
        {
          detail: {
            summary: 'Public showcase (SPA fallback)',
            tags: ['Showcase'],
          },
        },
      )
      .get('/_expo/*', ({ set, request }) => serveClientRootAsset(set, request), {
        detail: {
          summary: 'Expo web runtime (worker and bundles requested from origin root)',
          tags: ['Client'],
        },
      })
      .get('/assets/*', ({ set, request }) => serveClientRootAsset(set, request), {
        detail: {
          summary: 'Expo web static assets requested from origin root',
          tags: ['Client'],
        },
      })
      .use(
        showcaseUiAvailable
          ? await staticPlugin({
              assets: showcaseDistPath,
              prefix: '/_showcase',
              alwaysStatic: true,
            })
          : new Elysia(),
      )
      // Expo Router only recognises `/`. An F5 on `/StorySelection` (or whatever React Navigation has
      // written into the bar) has to come back to the root, not serve the index at that path - otherwise
      // the Router shows unmatched. The API and /showcase were already registered above.
      .get(
        '/*',
        ({ set, path: requestPath }) => {
          if (isApiOrLegacyApiPath(requestPath)) {
            set.status = 404;
            return { message: 'Not found' };
          }
          if (clientUiAvailable) {
            set.status = 302;
            set.headers.location = '/';
            return;
          }
          set.status = 404;
          return { message: 'Not found' };
        },
        {
          detail: {
            summary: 'Refresh fallback to the hosted client',
            description:
              'Unknown non-API paths redirect to / so a refresh never lands on an Expo Router unmatched screen.',
            tags: ['Client'],
          },
        },
      )
  );
}
