import { cookie } from '@elysiajs/cookie';
import { cors } from '@elysiajs/cors';
import { jwt } from '@elysiajs/jwt';
import { Elysia, t } from 'elysia';
import { existsSync, readFileSync } from 'fs';
import * as path from 'path';
import {
  adminDistPath as resolveAdminDistPath,
  clientDistPath as resolveClientDistPath,
  desktopIconPath,
  landingDistPath as resolveLandingDistPath,
  showcaseDistPath as resolveShowcaseDistPath,
} from './config/resourceRoot';
import {
  CLIENT_APP_ISOLATION_HEADERS,
  HOSTED_CLIENT_PATH_PREFIX,
  hostedClientRelativePath,
  isHostedClientPath,
  isShowcasePath,
  resolveHostedClientFile,
  SHOWCASE_PATH_PREFIX,
} from './services/hostedClient';
import { deliverDistFile } from './services/distStaticDelivery';
import { hostedClientDelivery, hostedClientDeliveryInput } from './services/hostedClientDelivery';
import { sendStaticDelivery } from './services/staticDelivery';
import { env } from './config/env';
import { createApiRoutes, isApiOrLegacyApiPath } from './api';
import { requestAudit } from './plugins/requestAudit';
import { showcaseSettingsService } from './services/ShowcaseSettingsService';
import { AppError } from './utils/errors';
import { logger } from './utils/logger';

/**
 * Co-hosting the admin panel: bringing the API up already serves the web app alongside it, in the
 * same process and port, with no need for a second deploy. `apps/admin` is still built separately
 * (`bun run build`, which runs `vite build` - see apps/admin/package.json); what changes here is only
 * serving the static result.
 *
 * The app's prefix is `/admin` (static files + the SPA fallback below); the JSON API it uses lives at
 * `/api/admin/*`, so the two do not fight over the same URL space. If the build does not exist yet
 * (dev without `bun run build`, or the API running on its own), that does not take the server down -
 * only the panel is unavailable, the API carries on as usual.
 *
 * Resolved by `resourceRoot` (not `process.cwd()`): in the checkout it points at `apps/admin/dist`;
 * in the Keres Server zip, at the `admin-dist` next to the executable.
 */
const adminDistPath = resolveAdminDistPath();
const adminDistIndexPath = path.join(adminDistPath, 'index.html');
const adminUiAvailable = existsSync(adminDistIndexPath);
/** Generated by the admin Vite build from desktop_icon.png (png-to-ico). */
const adminFaviconPath = path.join(adminDistPath, 'favicon.ico');
/**
 * The public site (Showcase) is `apps/admin`'s *second* build output - same project, another entry
 * point (`showcase.html`, `vite.showcase.config.ts`). The static files live under `/_showcase/`
 * (Vite's `base`) and the *pages* live at the root: mounting the static files directly at `/` would
 * make them shadow the API routes. See the catch-all at the end of the file.
 */
const showcaseDistPath = resolveShowcaseDistPath();
const showcaseDistIndexPath = path.join(showcaseDistPath, 'index.html');
const showcaseUiAvailable = existsSync(showcaseDistIndexPath);
/** The same .ico, generated from the same PNG, by the public site's build. */
const showcaseFaviconPath = path.join(showcaseDistPath, 'favicon.ico');
const clientDistPath = resolveClientDistPath();
const clientDistIndexPath = path.join(clientDistPath, 'index.html');
const clientUiAvailable = existsSync(clientDistIndexPath);
/**
 * The landing page (`apps/site`'s second build output). Like the showcase, its static files
 * live under their own prefix (`/_landing/`, Vite's `base`) and the *page* lives at the root:
 * mounting the files directly at `/` would shadow the API routes. Unlike the other bundles,
 * a missing one stays silent at boot - the landing is opt-in and off by default, so most
 * servers will never build it.
 */
const landingDistPath = resolveLandingDistPath();
const landingDistIndexPath = path.join(landingDistPath, 'index.html');
const landingUiAvailable = existsSync(landingDistIndexPath);
/** The same .ico, generated from the same PNG, by the landing page's build. */
const landingFaviconPath = path.join(landingDistPath, 'favicon.ico');

/** Fallback before an admin build exists — same PNG desktop uses, not copied into admin. */
const desktopIconFilePath = desktopIconPath();

/** Headers for the co-hosted admin SPA (static assets + HTML fallback). Not applied to `/api/admin/*`. */
const ADMIN_UI_SECURITY_HEADERS: Record<string, string> = {
  'Content-Security-Policy':
    "default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'",
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'no-referrer',
  'X-Frame-Options': 'DENY',
};

function applyAdminUiSecurityHeaders(set: { headers: Record<string, string | number> }): void {
  for (const [name, value] of Object.entries(ADMIN_UI_SECURITY_HEADERS)) {
    set.headers[name] = value;
  }
}

function applyClientAppIsolationHeaders(set: { headers: Record<string, string | number> }): void {
  for (const [name, value] of Object.entries(CLIENT_APP_ISOLATION_HEADERS)) {
    set.headers[name] = value;
  }
}

/**
 * The admin panel: a file of its build, or - for a route of the panel that is not a file (say,
 * /admin/users, which React Router resolves in the browser) - the same index.html. Without that
 * fallback an F5 on /admin/users would give a 404.
 *
 * Shared by `/admin` and `/admin/*`: the router sees them as two paths, and only one of them used to be
 * registered, so `/admin` fell to the catch-all and was sent to the root while `/admin/` opened the panel.
 */
async function serveAdminUi(
  set: { status?: number | string; headers: Record<string, string | number> },
  request: Request,
  requestPath: string,
): Promise<Uint8Array | string | Response | { message: string }> {
  // Do not let the removed `/admin/api/*` contract become a 200 with index.html.
  if (requestPath === '/admin/api' || requestPath.startsWith('/admin/api/')) {
    set.status = 404;
    return { message: 'Not found' };
  }
  if (!adminUiAvailable) {
    set.status = 404;
    return { message: "Admin UI not built. Run 'bun run build' in apps/api first." };
  }
  applyAdminUiSecurityHeaders(set);
  // A file of the build (compressed and cacheable, see `StaticDelivery`)...
  const file = await deliverDistFile(adminDistPath, requestPath.slice('/admin'.length), request);
  if (file) return sendStaticDelivery(set, file);
  // ...otherwise, the SPA fallback.
  // Node/Vitest has no `Bun.file`; the HTML is tiny so a sync read is fine.
  set.headers['content-type'] = 'text/html; charset=utf-8';
  return readFileSync(adminDistIndexPath, 'utf8');
}

/**
 * The hosted client: its entry page and everything it loads, all under `/client`. The entry is what the
 * administrator can switch off (`isHostedClientEnabled`); the assets it asks for are served regardless,
 * as they always were - without the entry nobody asks for them, and a database query per asset would be
 * a poor trade.
 */
async function serveHostedClient(
  set: { status?: number | string; headers: Record<string, string | number> },
  request: Request,
): Promise<Uint8Array | string | Response | { message: string }> {
  if (!clientUiAvailable) {
    set.status = 404;
    return { message: 'Not found' };
  }
  const resolved = resolveHostedClientFile(
    clientDistPath,
    hostedClientRelativePath(new URL(request.url).pathname),
  );
  if (!resolved) {
    set.status = 404;
    return { message: 'Not found' };
  }
  // The same default as the root had: on while the database is starting up or is down.
  if (resolved.html && !(await showcaseSettingsService.isHostedClientEnabled().catch(() => true))) {
    set.status = 404;
    return { message: 'Not found' };
  }
  const delivery = await hostedClientDelivery.deliver({
    ...hostedClientDeliveryInput(clientDistPath, resolved.filePath, resolved.html),
    request: {
      acceptEncoding: request.headers.get('accept-encoding'),
      ifNoneMatch: request.headers.get('if-none-match'),
    },
  });
  applyClientAppIsolationHeaders(set);
  return sendStaticDelivery(set, delivery);
}

if (!showcaseUiAvailable) {
  logger.warn(
    `Showcase UI not built - the public site will be unavailable. Run 'bun run admin:build' to enable it.`,
  );
}

if (!adminUiAvailable) {
  logger.warn(
    `Admin UI not built - /admin will 404. Run 'bun run build' in apps/api (or apps/admin) to enable it.`,
  );
}

if (!clientUiAvailable) {
  logger.warn(
    `Hosted client not built - /client will not serve the web app. Run 'bun run client:build:hosted' to enable it.`,
  );
}

/** pg/network error codes that mean "couldn't reach or lost the database", not an app bug. */
const DB_CONNECTIVITY_ERROR_CODES = new Set([
  'ECONNREFUSED',
  'ENOTFOUND',
  'ETIMEDOUT',
  'EHOSTUNREACH',
  'ENETUNREACH',
  'EAI_AGAIN',
  '57P03', // Postgres: cannot_connect_now
]);

export function isDatabaseConnectivityError(error: unknown): boolean {
  let current: unknown = error;
  // drizzle/pg wrap the root network error in `.cause`, sometimes more than one layer deep.
  for (let depth = 0; current && depth < 5; depth++) {
    const code = (current as { code?: unknown }).code;
    if (typeof code === 'string' && DB_CONNECTIVITY_ERROR_CODES.has(code)) {
      return true;
    }
    current = (current as { cause?: unknown }).cause;
  }
  return false;
}

// Define a placeholder type for the JWT payload
// In a real application, this would be derived from your User entity
export interface JWTPayload {
  userId: string;
  username: string;
}

/** Creates the application without migrating the database, reconciling the admin or opening a port. */
export async function createApp() {
  return (
    new Elysia()
      .use(cookie())
      .use(
        jwt({
          name: 'jwt',
          secret: env.JWT_SECRET,
          exp: '1h', // Access token expiration
          schema: t.Object({
            // Define schema for JWT payload
            userId: t.String(),
            username: t.String(),
          }),
        }),
      )
      .use(
        cors({
          // No client (mobile, desktop, web export, admin panel) authenticates via cookies -
          // every one of them attaches `Authorization: Bearer <token>` itself (see apiClient.ts
          // on the client and admin sides), so nothing actually needs the browser to send
          // cookies cross-origin. The default `credentials: true` combined with the default
          // `origin: true` (reflects any request Origin back) let any third-party site make
          // credentialed requests using this app's httpOnly auth cookies and read the response.
          // Disabling credentials here closes that off while keeping `origin: true`, which this
          // self-hosted, multi-deployment app still needs (there's no fixed set of client
          // origins to allowlist - every self-hoster's install is its own origin).
          credentials: false,
        }),
      )
      .derive(async ({ jwt, headers, cookie }) => {
        let token: string | null | undefined = headers['authorization']?.startsWith('Bearer ')
          ? headers['authorization'].slice(7)
          : null;

        if (!token && typeof cookie['access_token'].value === 'string') {
          token = cookie['access_token'].value;
        }

        if (!token) {
          // If no token, user is not authenticated.
          // We don't throw an error here, but rather return null for the user,
          // allowing routes to decide if authentication is mandatory.
          return { user: null };
        }

        // An invalid/expired token is treated exactly like no token at all - this `.derive()`
        // runs on every request, including public ones (GET /api/kerescheck, GET /api/swagger, POST
        // /auth/login...). Throwing 401 here used to reject those too, just because a client
        // happened to carry a stale token; each route that actually requires auth already does
        // its own `if (!user) { 401 }` check right after this runs, so nothing is lost by
        // deferring the rejection to there instead.
        try {
          const payload = await jwt.verify(token);
          return { user: (payload || null) as JWTPayload | null };
        } catch {
          return { user: null };
        }
      })
      // Who did what, for the administrators: after the session is known, before any route.
      .use(requestAudit)
      .onError(({ code, error, set, path, request, user, params }) => {
        const err = error instanceof Error ? error : new Error(String(error));
        const label = `${request.method} ${path}`;
        const userId = (user as JWTPayload | null)?.userId ?? null;
        // Only routes with a :storyId in their params carry this - it does not force the field where it is
        // not meaningful (not every route is scoped to a story).
        const storyId = (params as { storyId?: string } | undefined)?.storyId ?? null;

        // A route that deliberately rejected with AppError (any status, including 500)
        // already chose a safe, user-facing message - relay it as-is.
        if (err instanceof AppError) {
          set.status = err.status;
          logger.warn(`Rejected request: ${label}`, {
            status: err.status,
            message: err.message,
            userId,
            storyId,
          });
          return { message: err.message };
        }

        // Route handlers that deliberately picked a non-500 status before throwing a plain
        // Error (401/403/404/409...) already chose a safe message too - relay it as-is.
        // 500 is excluded here because Elysia defaults untouched status to 500 for any
        // unclassified thrown error, so it can't tell "the app chose 500" from "nothing did".
        if (typeof set.status === 'number' && set.status !== 500) {
          logger.warn(`Rejected request: ${label}`, {
            status: set.status,
            message: err.message,
            userId,
            storyId,
          });
          return { message: err.message };
        }

        if (isDatabaseConnectivityError(err)) {
          set.status = 503;
          logger.error(`Database unreachable while handling ${label}`, err, {
            code,
            userId,
            storyId,
          });
          return { message: 'Service temporarily unavailable. Please try again shortly.' };
        }

        // Anything else is unexpected - never leak internals (SQL, stack traces) to the client.
        set.status = 500;
        logger.error(`Unhandled error while handling ${label}`, err, { code, userId, storyId });
        return { message: 'Internal server error.' };
      })
      .get(
        '/',
        async ({ set }) => {
          // The root resolves in order: the landing page when the administrator enabled it, the
          // hosted client at /client, the showcase, and finally the API docs. Each step needs
          // both its build and its switch - an enabled page whose bundle was never built falls
          // through to the next, so the root always answers with something useful. It has never
          // depended on the database: while it is starting up or is down, the defaults (landing
          // off, client on) apply rather than trading a useful page for a 503.
          const settings = await showcaseSettingsService.getOrCreate().catch(() => null);
          const landingEnabled = settings?.isLandingEnabled ?? false;
          const hostedClientEnabled = settings?.isHostedClientEnabled ?? true;
          if (landingUiAvailable && landingEnabled) {
            applyAdminUiSecurityHeaders(set);
            set.headers['content-type'] = 'text/html; charset=utf-8';
            return readFileSync(landingDistIndexPath, 'utf8');
          }
          if (clientUiAvailable && hostedClientEnabled) {
            set.status = 302;
            set.headers.location = `${HOSTED_CLIENT_PATH_PREFIX}/`;
            return;
          }
          if (showcaseUiAvailable && (await showcaseSettingsService.isEnabled())) {
            set.status = 302;
            set.headers.location = SHOWCASE_PATH_PREFIX;
            return;
          }
          set.status = 302;
          set.headers.location = '/api/swagger';
          return;
        },
        {
          detail: {
            summary: 'Origin root (landing, hosted client, showcase or Swagger)',
            description:
              'Serves the landing page when enabled, else redirects to the hosted web client at /client, the showcase, or the API docs.',
            tags: ['Client'],
          },
        },
      )
      // `/client` and `/client/` are one path to the router, so there is no redirect between them: it
      // would answer itself forever. The entry is the same either way.
      .get('/client', ({ set, request }) => serveHostedClient(set, request), {
        detail: { summary: 'Hosted Keres client (entry)', tags: ['Client'] },
      })
      .get('/client/*', ({ set, request }) => serveHostedClient(set, request), {
        detail: {
          summary: 'Hosted Keres client',
          description:
            'Serves the web export of apps/client built for /client (KERES_WEB_BASE_URL), with COOP/COEP so expo-sqlite can use SharedArrayBuffer. A path with no file falls back to the entry page.',
          tags: ['Client'],
        },
      })
      .get(
        '/favicon.ico',
        ({ set }) => {
          // The panel, the public site and the landing page generate the same .ico, from the same
          // PNG - any one works. Looking in all keeps the tab from having no icon on a server that
          // only built one of them; the client's PNG is the last resort, for when no build exists yet.
          const generatedIcoPath = [adminFaviconPath, showcaseFaviconPath, landingFaviconPath].find(
            (candidate) => existsSync(candidate),
          );
          const filePath = generatedIcoPath ?? desktopIconFilePath;
          const useGeneratedIco = !!generatedIcoPath;
          if (!existsSync(filePath)) {
            set.status = 404;
            return { message: 'Not found' };
          }
          set.headers['content-type'] = useGeneratedIco ? 'image/x-icon' : 'image/png';
          set.headers['cache-control'] = 'public, max-age=86400';
          // `readFileSync` instead of `Bun.file`: this route is hit by the Node/Vitest suite
          // (`kerescheck.test.ts`) as well as Bun in production. The file is a few KB.
          return new Uint8Array(readFileSync(filePath));
        },
        {
          detail: {
            summary: 'Favicon',
            description:
              'Serves the ICO generated at web build time from apps/client desktop_icon.png (same source as apps/desktop).',
            tags: ['Admin'],
          },
        },
      )
      .use(createApiRoutes())
      .onAfterHandle(({ request, set }) => {
        const pathname = new URL(request.url).pathname;
        if (isHostedClientPath(pathname)) {
          applyClientAppIsolationHeaders(set);
          return;
        }
        if (pathname.startsWith('/admin')) {
          applyAdminUiSecurityHeaders(set);
        }
        if (
          isShowcasePath(pathname) ||
          pathname.startsWith('/_showcase') ||
          pathname.startsWith('/_landing')
        ) {
          applyAdminUiSecurityHeaders(set);
        }
      })
      // No compatibility shim: before the panel fallback could return its HTML, the old
      // administrative endpoints receive the same JSON 404 as any removed API route.
      .all('/admin/api', ({ set }) => {
        set.status = 404;
        return { message: 'Not found' };
      })
      .all('/admin/api/*', ({ set }) => {
        set.status = 404;
        return { message: 'Not found' };
      })
      .get(
        '/admin',
        ({ set, request, path: requestPath }) => serveAdminUi(set, request, requestPath),
        {
          detail: {
            summary: 'Admin panel (single-page app, entry without the slash)',
            tags: ['Admin'],
          },
        },
      )
      .get(
        '/admin/*',
        ({ set, request, path: requestPath }) => serveAdminUi(set, request, requestPath),
        {
          detail: {
            summary: 'Admin panel (single-page app)',
            description: 'Serves the built apps/admin SPA and its client-side routes.',
            tags: ['Admin'],
          },
        },
      )
      .get(
        '/app',
        ({ set }) => {
          set.status = 302;
          set.headers.location = '/';
        },
        {
          detail: {
            summary: 'Legacy hosted-client path',
            description:
              'The web client used to live at /app, and then at the root; it is under /client now.',
            tags: ['Client'],
          },
        },
      )
      .get(
        '/app/*',
        ({ set }) => {
          set.status = 302;
          set.headers.location = '/';
        },
        {
          detail: {
            summary: 'Legacy hosted-client path',
            tags: ['Client'],
          },
        },
      )
      .get(
        '/showcase',
        async ({ set }) => {
          if (!showcaseUiAvailable || !(await showcaseSettingsService.isEnabled())) {
            set.status = 404;
            return { message: 'Not found' };
          }
          applyAdminUiSecurityHeaders(set);
          set.headers['content-type'] = 'text/html; charset=utf-8';
          return readFileSync(showcaseDistIndexPath, 'utf8');
        },
        {
          detail: {
            summary: 'Public showcase',
            description: 'Lists stories published on this server.',
            tags: ['Showcase'],
          },
        },
      )
      .get(
        '/showcase/*',
        async ({ set }) => {
          if (!showcaseUiAvailable || !(await showcaseSettingsService.isEnabled())) {
            set.status = 404;
            return { message: 'Not found' };
          }
          applyAdminUiSecurityHeaders(set);
          set.headers['content-type'] = 'text/html; charset=utf-8';
          return readFileSync(showcaseDistIndexPath, 'utf8');
        },
        {
          detail: {
            summary: 'Public showcase (SPA fallback)',
            tags: ['Showcase'],
          },
        },
      )
      // The static files of the public site and of the landing page, under the prefix Vite built them for.
      // Their pages are served at the root and at /showcase; only what they load comes from here.
      .get(
        '/_showcase/*',
        async ({ set, request, path: requestPath }) => {
          const file = showcaseUiAvailable
            ? await deliverDistFile(
                showcaseDistPath,
                requestPath.slice('/_showcase'.length),
                request,
              )
            : null;
          if (!file) {
            set.status = 404;
            return { message: 'Not found' };
          }
          return sendStaticDelivery(set, file);
        },
        { detail: { summary: 'Showcase static files', tags: ['Showcase'] } },
      )
      .get(
        '/_landing/*',
        async ({ set, request, path: requestPath }) => {
          const file = landingUiAvailable
            ? await deliverDistFile(landingDistPath, requestPath.slice('/_landing'.length), request)
            : null;
          if (!file) {
            set.status = 404;
            return { message: 'Not found' };
          }
          return sendStaticDelivery(set, file);
        },
        { detail: { summary: 'Landing page static files', tags: ['Client'] } },
      )
      // A path nobody answers - an old bookmark, a stale reload - goes back to the root, which sends it
      // on. The API, /showcase, /client and /_landing were already registered above.
      .get(
        '/*',
        ({ set, path: requestPath }) => {
          if (isApiOrLegacyApiPath(requestPath)) {
            set.status = 404;
            return { message: 'Not found' };
          }
          if (clientUiAvailable) {
            set.status = 302;
            set.headers.location = '/';
            return;
          }
          set.status = 404;
          return { message: 'Not found' };
        },
        {
          detail: {
            summary: 'Fallback to the root',
            description: 'Unknown non-API paths redirect to /.',
            tags: ['Client'],
          },
        },
      )
  );
}
