/** UI refresh events emitted after applying remote entity changes. */
export const SYNC_ENTITY_EVENTS: Record<string, string> = {
  Story: 'story_changed',
  Character: 'character_changed',
  CharacterRelation: 'character_relation_changed',
  CharacterScene: 'character_scene_changed',
  Tag: 'tag_changed',
  TagRelation: 'tag_relation_changed',
  Note: 'note_changed',
  NoteRelation: 'note_relation_changed',
  WorldRule: 'worldrule_changed',
  Location: 'location_changed',
  LocationRelation: 'location_relation_changed',
  Chapter: 'chapter_changed',
  Scene: 'scene_changed',
  Choice: 'choice_changed',
  ChoiceCheckGroup: 'choice_check_group_changed',
  ChoiceCheck: 'choice_check_changed',
  Effect: 'effect_changed',
  Item: 'item_changed',
  ItemJourney: 'item_journey_changed',
  Plot: 'plot_changed',
  PlotScene: 'plot_scene_changed',
  Gallery: 'gallery_changed',
  GalleryRelation: 'gallery_relation_changed',
  StorySchemaField: 'story_schema_field_changed',
  AttributeValue: 'attribute_value_changed',
  Favorite: 'favorite_changed',
  SeeAlsoRelation: 'see_also_relation_changed',
  Comment: 'comment_changed',
  Suggestion: 'suggestion_changed',
  Stat: 'stat_changed',
  StatStrength: 'stat_strength_changed',
  StatRelation: 'stat_relation_changed',
  Mode: 'mode_changed',
};

export const FAVORITE_TARGET_EVENTS: Record<string, string> = {
  Story: 'story_changed',
  Character: 'character_changed',
  Chapter: 'chapter_changed',
  Location: 'location_changed',
  Scene: 'scene_changed',
  Note: 'note_changed',
  WorldRule: 'worldrule_changed',
  Item: 'item_changed',
  Gallery: 'gallery_changed',
  Tag: 'tag_changed',
};
