import type { HelpSection } from './types';

export const helpSections: HelpSection[] = [
  {
    id: 'start',
    titleKey: 'help_section_start',
    icon: 'compass-outline',
    pageIds: [
      'what-is-keres',
      'first-story',
      'how-keres-organizes',
      'getting-around',
      'lists-and-search',
      'using-this-help',
      'story-devices',
    ],
  },
  {
    id: 'stories',
    titleKey: 'help_section_stories',
    icon: 'book-outline',
    pageIds: [
      'story-list',
      'create-story',
      'story-type',
      'story-settings',
      'calendars',
      'story-dashboard',
      'story-analysis',
      'import-export',
      'publish-story',
      'packs',
      'example-stories',
    ],
  },
  {
    id: 'elements',
    titleKey: 'help_section_elements',
    icon: 'people-outline',
    pageIds: [
      'characters',
      'character-relationships',
      'character-modes',
      'stats',
      'narrative-elements',
      'chapters',
      'scenes',
      'scene-timing',
      'plots',
      'locations',
      'location-map',
      'items',
      'item-journeys',
      'world-rules',
      'notes',
      'tags',
      'gallery',
      'favorites',
    ],
  },
  {
    id: 'branching',
    titleKey: 'help_section_branching',
    icon: 'git-branch-outline',
    pageIds: [
      'branching-basics',
      'choices',
      'story-map',
      'choice-conditions',
      'effects',
      'story-state',
    ],
  },
  {
    id: 'annotate',
    titleKey: 'help_section_annotate',
    icon: 'create-outline',
    pageIds: ['comments', 'see-also', 'custom-attributes', 'suggestions'],
  },
  {
    id: 'preferences',
    titleKey: 'help_section_preferences',
    icon: 'settings-outline',
    pageIds: ['app-settings'],
  },
  {
    id: 'accounts',
    titleKey: 'help_section_accounts',
    icon: 'people-circle-outline',
    pageIds: [
      'what-is-a-server',
      'add-server',
      'your-profile',
      'change-password',
      'friends',
      'collaborators',
      'account-limits',
    ],
  },
  {
    id: 'sync',
    titleKey: 'help_section_sync',
    icon: 'sync-outline',
    pageIds: ['sync-basics', 'sync-conflicts', 'activity-log'],
  },
  {
    id: 'support',
    titleKey: 'help_section_support',
    icon: 'help-buoy-outline',
    pageIds: ['troubleshooting', 'data-and-backup', 'glossary', 'faq'],
  },
];

export const helpPageIds = helpSections.flatMap((section) => section.pageIds);
