import type { HelpPageId } from './types';

/**
 * Every reachable app route with a reader-facing header points to its closest
 * help page. Parent drawer routes are retained as fallbacks while nested stacks
 * are loading or restoring state.
 */
export const screenHelpPage: Record<string, HelpPageId> = {
  StorySelectionMain: 'story-list',
  StorySelectionScreen: 'story-list',
  StoryForm: 'create-story',
  ExampleStories: 'example-stories',
  PacksDrawer: 'packs',
  PackList: 'packs',
  PackForm: 'packs',
  PackBrowse: 'packs',
  ShippedPacks: 'packs',
  ImportExport: 'import-export',
  PublishStory: 'publish-story',
  Settings: 'app-settings',
  ServerManagementDrawer: 'what-is-a-server',
  ServerManagement: 'what-is-a-server',
  ServerRegistration: 'add-server',
  MyProfile: 'your-profile',
  ChangePassword: 'change-password',
  FriendshipDrawer: 'friends',
  FriendshipList: 'friends',
  FriendshipForm: 'friends',
  FriendDetail: 'friends',
  MainDashboard: 'story-dashboard',
  GlobalSearch: 'lists-and-search',
  CharactersStack: 'characters',
  Characters: 'characters',
  CharacterDetail: 'characters',
  CharacterForm: 'characters',
  NarrativeElementsStack: 'narrative-elements',
  NarrativeElements: 'narrative-elements',
  ChapterDetail: 'chapters',
  ChapterForm: 'chapters',
  SceneDetail: 'scenes',
  SceneForm: 'scenes',
  ChoiceDetail: 'choices',
  ChoiceForm: 'choices',
  ChoiceView: 'choices',
  StoryTimeline: 'scene-timing',
  PlotsStack: 'plots',
  Plots: 'plots',
  PlotDetail: 'plots',
  PlotForm: 'plots',
  PlotMatrix: 'plots',
  PlotProgress: 'plots',
  PlotReader: 'plots',
  Routes: 'routes',
  RouteDetail: 'routes',
  RouteForm: 'routes',
  RouteSteps: 'routes',
  RouteReader: 'routes',
  StoryNavigator: 'routes',
  LocationsStack: 'locations',
  Locations: 'locations',
  LocationDetail: 'locations',
  LocationForm: 'locations',
  LocationView: 'location-map',
  LocationMapList: 'location-map',
  LocationMap: 'location-map',
  ItemsStack: 'items',
  Items: 'items',
  ItemDetail: 'items',
  ItemForm: 'items',
  ItemJourneys: 'item-journeys',
  ItemJourneyDetail: 'item-journeys',
  ItemJourneyForm: 'item-journeys',
  TagsStack: 'tags',
  Tags: 'tags',
  TagDetail: 'tags',
  TagForm: 'tags',
  WorldRulesStack: 'world-rules',
  WorldRules: 'world-rules',
  WorldRuleDetail: 'world-rules',
  WorldRuleForm: 'world-rules',
  NotesStack: 'notes',
  Notes: 'notes',
  NoteDetail: 'notes',
  NoteForm: 'notes',
  GalleryStack: 'gallery',
  GalleryList: 'gallery',
  GalleryDetail: 'gallery',
  BoardsStack: 'boards',
  BoardList: 'boards',
  BoardCanvas: 'boards',
  CharacterRelationView: 'character-relationships',
  StorySchemaStack: 'custom-attributes',
  StorySchemaList: 'custom-attributes',
  /*
   * The index lists four areas, so there is no single page it belongs to. Custom attributes is the
   * one it is most often opened for, and the page links on to the other three.
   */
  CustomizationIndex: 'custom-attributes',
  CustomizationStack: 'custom-attributes',
  Vocabulary: 'custom-attributes',
  StorySchemaFieldForm: 'custom-attributes',
  Suggestions: 'suggestions',
  SuggestionUsage: 'suggestions',
  CommentsStack: 'comments',
  CommentsList: 'comments',
  OperationLogStack: 'activity-log',
  OperationLog: 'activity-log',
  OperationLogDetail: 'activity-log',
  StoryAnalysis: 'story-analysis',
  StorySettings: 'story-settings',
  StoryCalendarList: 'calendars',
  StoryCalendarForm: 'calendars',
  StoryAgenda: 'calendars',
  StatList: 'stats',
  StatForm: 'stats',
  StatLadder: 'stats',
  StatComparison: 'stats',
  StatRanking: 'stats',
};
