import { HelpPageId } from './types';

/**
 * Every reachable app route with a reader-facing header points to its closest
 * help page. Parent drawer routes are retained as fallbacks while nested stacks
 * are loading or restoring state.
 */
export const screenHelpPage: Record<string, HelpPageId> = {
  StorySelectionMain: 'story-list',
  StorySelectionScreen: 'story-list',
  StoryForm: 'create-story',
  ExampleStories: 'example-stories',
  ImportExport: 'import-export',
  PublishStory: 'publish-story',
  Settings: 'app-settings',
  ServerManagementDrawer: 'what-is-a-server',
  ServerManagement: 'what-is-a-server',
  ServerRegistration: 'add-server',
  MyProfile: 'your-profile',
  ChangePassword: 'change-password',
  FriendshipDrawer: 'friends',
  FriendshipList: 'friends',
  FriendshipForm: 'friends',
  FriendDetail: 'friends',
  MainDashboard: 'story-dashboard',
  GlobalSearch: 'lists-and-search',
  CharactersStack: 'characters',
  Characters: 'characters',
  CharacterDetail: 'characters',
  CharacterForm: 'characters',
  ChaptersStack: 'chapters',
  Chapters: 'chapters',
  ChapterDetail: 'chapters',
  ChapterForm: 'chapters',
  ScenesStack: 'scenes',
  Scenes: 'scenes',
  SceneDetail: 'scenes',
  SceneForm: 'scenes',
  ChoicesStack: 'choices',
  Choices: 'choices',
  ChoiceDetail: 'choices',
  ChoiceForm: 'choices',
  ChoiceView: 'choices',
  LocationsStack: 'locations',
  Locations: 'locations',
  LocationDetail: 'locations',
  LocationForm: 'locations',
  LocationView: 'location-map',
  ItemsStack: 'items',
  Items: 'items',
  ItemDetail: 'items',
  ItemForm: 'items',
  ItemJourneysStack: 'item-journeys',
  ItemJourneys: 'item-journeys',
  ItemJourneyDetail: 'item-journeys',
  ItemJourneyForm: 'item-journeys',
  TagsStack: 'tags',
  Tags: 'tags',
  TagDetail: 'tags',
  TagForm: 'tags',
  WorldRulesStack: 'world-rules',
  WorldRules: 'world-rules',
  WorldRuleDetail: 'world-rules',
  WorldRuleForm: 'world-rules',
  NotesStack: 'notes',
  Notes: 'notes',
  NoteDetail: 'notes',
  NoteForm: 'notes',
  GalleryStack: 'gallery',
  GalleryList: 'gallery',
  GalleryDetail: 'gallery',
  CharacterRelationsStack: 'character-relationships',
  CharacterRelations: 'character-relationships',
  CharacterRelationView: 'character-relationships',
  StorySchemaStack: 'custom-attributes',
  StorySchemaList: 'custom-attributes',
  StorySchemaFieldForm: 'custom-attributes',
  Suggestions: 'suggestions',
  CommentsStack: 'comments',
  CommentsList: 'comments',
  OperationLogStack: 'activity-log',
  OperationLog: 'activity-log',
  OperationLogDetail: 'activity-log',
  StoryAnalysis: 'story-analysis',
  StorySettings: 'story-settings',
};
