import type { SQLiteDatabase } from 'expo-sqlite';

export default async function (db: SQLiteDatabase) {
  await db.execAsync(`
  ALTER TABLE "chapters" ADD "rank" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "scenes" ADD "rank" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "stats" ADD "rank" text DEFAULT '' NOT NULL;--> statement-breakpoint
ALTER TABLE "story_schema_fields" ADD "rank" text DEFAULT '' NOT NULL;--> statement-breakpoint
-- Ranks for rows written before ranks existed: the key each old position implies (rules/rank.ts rankAtPosition), then positions renumbered from the ranks, and tombstones placeless.
UPDATE "scenes" SET "rank" = CASE WHEN max("index", 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (max("index", 0)) + 1, 1) WHEN max("index", 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max("index", 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max("index", 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max("index", 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((min(max("index", 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max("index", 0), 242233) - 3906) % 62) + 1, 1) END WHERE "rank" = '';
--> statement-breakpoint
UPDATE "chapters" SET "rank" = CASE WHEN max("index", 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (max("index", 0)) + 1, 1) WHEN max("index", 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max("index", 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max("index", 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max("index", 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((min(max("index", 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max("index", 0), 242233) - 3906) % 62) + 1, 1) END WHERE "rank" = '';
--> statement-breakpoint
UPDATE "stats" SET "rank" = CASE WHEN max("order" + 1, 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (max("order" + 1, 0)) + 1, 1) WHEN max("order" + 1, 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max("order" + 1, 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max("order" + 1, 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max("order" + 1, 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((min(max("order" + 1, 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max("order" + 1, 0), 242233) - 3906) % 62) + 1, 1) END WHERE "rank" = '';
--> statement-breakpoint
UPDATE "story_schema_fields" SET "rank" = CASE WHEN max("order" + 1, 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (max("order" + 1, 0)) + 1, 1) WHEN max("order" + 1, 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max("order" + 1, 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max("order" + 1, 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max("order" + 1, 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((min(max("order" + 1, 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max("order" + 1, 0), 242233) - 3906) % 62) + 1, 1) END WHERE "rank" = '';
--> statement-breakpoint
UPDATE "scenes" SET "index" = 0 WHERE "is_deleted" = 1 AND "index" <> 0;
--> statement-breakpoint
UPDATE "chapters" SET "index" = 0 WHERE "is_deleted" = 1 AND "index" <> 0;
--> statement-breakpoint
UPDATE "stats" SET "order" = -1 WHERE "is_deleted" = 1 AND "order" <> -1;
--> statement-breakpoint
UPDATE "story_schema_fields" SET "order" = -1 WHERE "is_deleted" = 1 AND "order" <> -1;
--> statement-breakpoint
UPDATE "scenes" SET "index" = "numbered"."position" FROM (SELECT "id", ROW_NUMBER() OVER (PARTITION BY "story_id", "chapter_id" ORDER BY "rank", "id") AS "position" FROM "scenes" WHERE "is_deleted" = 0) AS "numbered" WHERE "scenes"."id" = "numbered"."id" AND "scenes"."index" <> "numbered"."position";
--> statement-breakpoint
UPDATE "chapters" SET "index" = "numbered"."position" FROM (SELECT "id", ROW_NUMBER() OVER (PARTITION BY "story_id", "type" ORDER BY "rank", "id") AS "position" FROM "chapters" WHERE "is_deleted" = 0) AS "numbered" WHERE "chapters"."id" = "numbered"."id" AND "chapters"."index" <> "numbered"."position";
--> statement-breakpoint
UPDATE "stats" SET "order" = "numbered"."position" FROM (SELECT "id", ROW_NUMBER() OVER (PARTITION BY "story_id" ORDER BY "rank", "id") - 1 AS "position" FROM "stats" WHERE "is_deleted" = 0) AS "numbered" WHERE "stats"."id" = "numbered"."id" AND "stats"."order" <> "numbered"."position";
--> statement-breakpoint
UPDATE "story_schema_fields" SET "order" = "numbered"."position" FROM (SELECT "id", ROW_NUMBER() OVER (PARTITION BY "story_id", "entity_type" ORDER BY "rank", "id") - 1 AS "position" FROM "story_schema_fields" WHERE "is_deleted" = 0) AS "numbered" WHERE "story_schema_fields"."id" = "numbered"."id" AND "story_schema_fields"."order" <> "numbered"."position";
--> statement-breakpoint
CREATE TRIGGER "scenes_rank_insert" AFTER INSERT ON "scenes" BEGIN UPDATE "scenes" SET "rank" = CASE WHEN max(NEW."index", 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (max(NEW."index", 0)) + 1, 1) WHEN max(NEW."index", 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max(NEW."index", 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max(NEW."index", 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max(NEW."index", 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((min(max(NEW."index", 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max(NEW."index", 0), 242233) - 3906) % 62) + 1, 1) END WHERE "id" = NEW."id" AND "rank" = ''; UPDATE "scenes" SET "index" = 0 WHERE "id" = NEW."id" AND "is_deleted" = 1 AND "index" <> 0; UPDATE "scenes" SET "index" = (SELECT COUNT(*) FROM "scenes" AS "other" WHERE "other"."story_id" IS "scenes"."story_id" AND "other"."chapter_id" IS "scenes"."chapter_id" AND "other"."is_deleted" = 0 AND ("other"."rank" < "scenes"."rank" OR ("other"."rank" = "scenes"."rank" AND "other"."id" <= "scenes"."id"))) WHERE "story_id" IS NEW."story_id" AND "chapter_id" IS NEW."chapter_id" AND "is_deleted" = 0; END;
--> statement-breakpoint
CREATE TRIGGER "scenes_rank_update" AFTER UPDATE OF "rank", "chapter_id", "is_deleted" ON "scenes" BEGIN UPDATE "scenes" SET "index" = 0 WHERE "id" = NEW."id" AND "is_deleted" = 1 AND "index" <> 0; UPDATE "scenes" SET "index" = (SELECT COUNT(*) FROM "scenes" AS "other" WHERE "other"."story_id" IS "scenes"."story_id" AND "other"."chapter_id" IS "scenes"."chapter_id" AND "other"."is_deleted" = 0 AND ("other"."rank" < "scenes"."rank" OR ("other"."rank" = "scenes"."rank" AND "other"."id" <= "scenes"."id"))) WHERE "story_id" IS OLD."story_id" AND "chapter_id" IS OLD."chapter_id" AND "is_deleted" = 0; UPDATE "scenes" SET "index" = (SELECT COUNT(*) FROM "scenes" AS "other" WHERE "other"."story_id" IS "scenes"."story_id" AND "other"."chapter_id" IS "scenes"."chapter_id" AND "other"."is_deleted" = 0 AND ("other"."rank" < "scenes"."rank" OR ("other"."rank" = "scenes"."rank" AND "other"."id" <= "scenes"."id"))) WHERE "story_id" IS NEW."story_id" AND "chapter_id" IS NEW."chapter_id" AND "is_deleted" = 0; END;
--> statement-breakpoint
CREATE TRIGGER "chapters_rank_insert" AFTER INSERT ON "chapters" BEGIN UPDATE "chapters" SET "rank" = CASE WHEN max(NEW."index", 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (max(NEW."index", 0)) + 1, 1) WHEN max(NEW."index", 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max(NEW."index", 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max(NEW."index", 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max(NEW."index", 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((min(max(NEW."index", 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max(NEW."index", 0), 242233) - 3906) % 62) + 1, 1) END WHERE "id" = NEW."id" AND "rank" = ''; UPDATE "chapters" SET "index" = 0 WHERE "id" = NEW."id" AND "is_deleted" = 1 AND "index" <> 0; UPDATE "chapters" SET "index" = (SELECT COUNT(*) FROM "chapters" AS "other" WHERE "other"."story_id" IS "chapters"."story_id" AND "other"."type" IS "chapters"."type" AND "other"."is_deleted" = 0 AND ("other"."rank" < "chapters"."rank" OR ("other"."rank" = "chapters"."rank" AND "other"."id" <= "chapters"."id"))) WHERE "story_id" IS NEW."story_id" AND "type" IS NEW."type" AND "is_deleted" = 0; END;
--> statement-breakpoint
CREATE TRIGGER "chapters_rank_update" AFTER UPDATE OF "rank", "type", "is_deleted" ON "chapters" BEGIN UPDATE "chapters" SET "index" = 0 WHERE "id" = NEW."id" AND "is_deleted" = 1 AND "index" <> 0; UPDATE "chapters" SET "index" = (SELECT COUNT(*) FROM "chapters" AS "other" WHERE "other"."story_id" IS "chapters"."story_id" AND "other"."type" IS "chapters"."type" AND "other"."is_deleted" = 0 AND ("other"."rank" < "chapters"."rank" OR ("other"."rank" = "chapters"."rank" AND "other"."id" <= "chapters"."id"))) WHERE "story_id" IS OLD."story_id" AND "type" IS OLD."type" AND "is_deleted" = 0; UPDATE "chapters" SET "index" = (SELECT COUNT(*) FROM "chapters" AS "other" WHERE "other"."story_id" IS "chapters"."story_id" AND "other"."type" IS "chapters"."type" AND "other"."is_deleted" = 0 AND ("other"."rank" < "chapters"."rank" OR ("other"."rank" = "chapters"."rank" AND "other"."id" <= "chapters"."id"))) WHERE "story_id" IS NEW."story_id" AND "type" IS NEW."type" AND "is_deleted" = 0; END;
--> statement-breakpoint
CREATE TRIGGER "stats_rank_insert" AFTER INSERT ON "stats" BEGIN UPDATE "stats" SET "rank" = CASE WHEN max(NEW."order" + 1, 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (max(NEW."order" + 1, 0)) + 1, 1) WHEN max(NEW."order" + 1, 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max(NEW."order" + 1, 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max(NEW."order" + 1, 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max(NEW."order" + 1, 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((min(max(NEW."order" + 1, 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max(NEW."order" + 1, 0), 242233) - 3906) % 62) + 1, 1) END WHERE "id" = NEW."id" AND "rank" = ''; UPDATE "stats" SET "order" = -1 WHERE "id" = NEW."id" AND "is_deleted" = 1 AND "order" <> -1; UPDATE "stats" SET "order" = (SELECT COUNT(*) FROM "stats" AS "other" WHERE "other"."story_id" IS "stats"."story_id" AND "other"."is_deleted" = 0 AND ("other"."rank" < "stats"."rank" OR ("other"."rank" = "stats"."rank" AND "other"."id" < "stats"."id"))) WHERE "story_id" IS NEW."story_id" AND "is_deleted" = 0; END;
--> statement-breakpoint
CREATE TRIGGER "stats_rank_update" AFTER UPDATE OF "rank", "is_deleted" ON "stats" BEGIN UPDATE "stats" SET "order" = -1 WHERE "id" = NEW."id" AND "is_deleted" = 1 AND "order" <> -1; UPDATE "stats" SET "order" = (SELECT COUNT(*) FROM "stats" AS "other" WHERE "other"."story_id" IS "stats"."story_id" AND "other"."is_deleted" = 0 AND ("other"."rank" < "stats"."rank" OR ("other"."rank" = "stats"."rank" AND "other"."id" < "stats"."id"))) WHERE "story_id" IS OLD."story_id" AND "is_deleted" = 0; UPDATE "stats" SET "order" = (SELECT COUNT(*) FROM "stats" AS "other" WHERE "other"."story_id" IS "stats"."story_id" AND "other"."is_deleted" = 0 AND ("other"."rank" < "stats"."rank" OR ("other"."rank" = "stats"."rank" AND "other"."id" < "stats"."id"))) WHERE "story_id" IS NEW."story_id" AND "is_deleted" = 0; END;
--> statement-breakpoint
CREATE TRIGGER "story_schema_fields_rank_insert" AFTER INSERT ON "story_schema_fields" BEGIN UPDATE "story_schema_fields" SET "rank" = CASE WHEN max(NEW."order" + 1, 0) < 62 THEN 'a' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (max(NEW."order" + 1, 0)) + 1, 1) WHEN max(NEW."order" + 1, 0) < 3906 THEN 'b' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max(NEW."order" + 1, 0) - 62) / 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((max(NEW."order" + 1, 0) - 62) % 62) + 1, 1) ELSE 'c' || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max(NEW."order" + 1, 0), 242233) - 3906) / 3844) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', (((min(max(NEW."order" + 1, 0), 242233) - 3906) / 62) % 62) + 1, 1) || substr('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', ((min(max(NEW."order" + 1, 0), 242233) - 3906) % 62) + 1, 1) END WHERE "id" = NEW."id" AND "rank" = ''; UPDATE "story_schema_fields" SET "order" = -1 WHERE "id" = NEW."id" AND "is_deleted" = 1 AND "order" <> -1; UPDATE "story_schema_fields" SET "order" = (SELECT COUNT(*) FROM "story_schema_fields" AS "other" WHERE "other"."story_id" IS "story_schema_fields"."story_id" AND "other"."entity_type" IS "story_schema_fields"."entity_type" AND "other"."is_deleted" = 0 AND ("other"."rank" < "story_schema_fields"."rank" OR ("other"."rank" = "story_schema_fields"."rank" AND "other"."id" < "story_schema_fields"."id"))) WHERE "story_id" IS NEW."story_id" AND "entity_type" IS NEW."entity_type" AND "is_deleted" = 0; END;
--> statement-breakpoint
CREATE TRIGGER "story_schema_fields_rank_update" AFTER UPDATE OF "rank", "entity_type", "is_deleted" ON "story_schema_fields" BEGIN UPDATE "story_schema_fields" SET "order" = -1 WHERE "id" = NEW."id" AND "is_deleted" = 1 AND "order" <> -1; UPDATE "story_schema_fields" SET "order" = (SELECT COUNT(*) FROM "story_schema_fields" AS "other" WHERE "other"."story_id" IS "story_schema_fields"."story_id" AND "other"."entity_type" IS "story_schema_fields"."entity_type" AND "other"."is_deleted" = 0 AND ("other"."rank" < "story_schema_fields"."rank" OR ("other"."rank" = "story_schema_fields"."rank" AND "other"."id" < "story_schema_fields"."id"))) WHERE "story_id" IS OLD."story_id" AND "entity_type" IS OLD."entity_type" AND "is_deleted" = 0; UPDATE "story_schema_fields" SET "order" = (SELECT COUNT(*) FROM "story_schema_fields" AS "other" WHERE "other"."story_id" IS "story_schema_fields"."story_id" AND "other"."entity_type" IS "story_schema_fields"."entity_type" AND "other"."is_deleted" = 0 AND ("other"."rank" < "story_schema_fields"."rank" OR ("other"."rank" = "story_schema_fields"."rank" AND "other"."id" < "story_schema_fields"."id"))) WHERE "story_id" IS NEW."story_id" AND "entity_type" IS NEW."entity_type" AND "is_deleted" = 0; END;

`);
}
