// This file is auto-generated by generate-migrations-index.js
// Do not modify this file directly.

import migration_1 from './0000_shocking_mister_sinister';
import migration_2 from './0001_glamorous_makkari';
import migration_3 from './0002_friendly_bishop';
import migration_4 from './0003_keen_the_captain';
import migration_5 from './0004_daffy_katie_power';
import migration_6 from './0005_aberrant_kronos';
import migration_7 from './0006_rainy_cardiac';
import migration_8 from './0007_medical_komodo';
import migration_9 from './0008_steep_spencer_smythe';
import migration_10 from './0009_nappy_nextwave';
import migration_11 from './0010_daffy_wolverine';
import migration_12 from './0011_smooth_goliath';
import migration_13 from './0012_moaning_thunderball';
import migration_14 from './0013_quiet_master_mold';
import migration_15 from './0014_little_junta';
import migration_16 from './0015_strong_archangel';
import migration_17 from './0016_fine_mercury';
import migration_18 from './0017_peaceful_darkstar';
import migration_19 from './0018_gallery_drop_owner';
import migration_20 from './0019_gallery_media';
import migration_21 from './0020_gallery_video_thumbnail';
import migration_22 from './0021_clumsy_spirit';
import migration_23 from './0022_odd_the_phantom';


const migrations = [
{ id: 1, name: '0000_shocking_mister_sinister', run: migration_1 },
  { id: 2, name: '0001_glamorous_makkari', run: migration_2 },
  { id: 3, name: '0002_friendly_bishop', run: migration_3 },
  { id: 4, name: '0003_keen_the_captain', run: migration_4 },
  { id: 5, name: '0004_daffy_katie_power', run: migration_5 },
  { id: 6, name: '0005_aberrant_kronos', run: migration_6 },
  { id: 7, name: '0006_rainy_cardiac', run: migration_7 },
  { id: 8, name: '0007_medical_komodo', run: migration_8 },
  { id: 9, name: '0008_steep_spencer_smythe', run: migration_9 },
  { id: 10, name: '0009_nappy_nextwave', run: migration_10 },
  { id: 11, name: '0010_daffy_wolverine', run: migration_11 },
  { id: 12, name: '0011_smooth_goliath', run: migration_12 },
  { id: 13, name: '0012_moaning_thunderball', run: migration_13 },
  { id: 14, name: '0013_quiet_master_mold', run: migration_14 },
  { id: 15, name: '0014_little_junta', run: migration_15 },
  { id: 16, name: '0015_strong_archangel', run: migration_16 },
  { id: 17, name: '0016_fine_mercury', run: migration_17 },
  { id: 18, name: '0017_peaceful_darkstar', run: migration_18 },
  { id: 19, name: '0018_gallery_drop_owner', run: migration_19 },
  { id: 20, name: '0019_gallery_media', run: migration_20 },
  { id: 21, name: '0020_gallery_video_thumbnail', run: migration_21 },
  { id: 22, name: '0021_clumsy_spirit', run: migration_22 },
  { id: 23, name: '0022_odd_the_phantom', run: migration_23 },
];

export default migrations;
